// AUTO-GENERATED by scripts/gen-bios-manifest.mjs — do not edit by hand.
// Source: The RetroBIOS Project (Abdess/retrobios) RetroArch/libretro System.dat.
// Only metadata (core-expected filename + verified hashes) is embedded; GameHub
// never distributes BIOS files.

export type BiosRegion = "World" | "USA" | "Japan" | "Europe" | "Asia" | "Other";

export interface BiosFile {
  /** exact filename the libretro core looks for in its system dir */
  file: string;
  md5: string;
  sha1: string;
  size: number;
  region: BiosRegion;
  description: string;
}

export interface BiosSystem {
  /** true when the console will not run without a BIOS (else BIOS is optional) */
  required: boolean;
  files: BiosFile[];
}

/** Per GameHub platform slug → the BIOS files that console can use. Systems that
 *  need no BIOS are absent. */
export const BIOS_MANIFEST: Record<string, BiosSystem> = {
  "3do": {
    required: true,
    files: [
    { file: "3do_arcade_saot.bin", md5: "8970fc987ab89a7f64da9f8a8c4333ff", sha1: "520d3d1b5897800af47f92efd2444a26b7a7dead", size: 524288, region: "World", description: "" },
    { file: "goldstar.bin", md5: "8639fd5e549bd6238cfee79e3e749114", sha1: "c4a2e5336f77fb5f743de1eea2cda43675ee2de7", size: 1048576, region: "Asia", description: "" },
    { file: "panafz1-kanji.bin", md5: "b8dc97f778a6245c58e064b0312e8281", sha1: "acd39a8fee1b9d2950d5ab447846c11fb31af63e", size: 933636, region: "World", description: "" },
    { file: "panafz1.bin", md5: "f47264dd47fe30f73ab3c010015c155b", sha1: "34bf189111295f74d7b7dfc1f304d98b8d36325a", size: 1048576, region: "Japan", description: "" },
    { file: "panafz10-norsa.bin", md5: "1477bda80dc33731a65468c1f5bcbee9", sha1: "f05e642322c03694f06a809c0b90fc27ac73c002", size: 1048576, region: "World", description: "" },
    { file: "panafz10.bin", md5: "51f2f43ae2f3508a14d9f56597e2d3ce", sha1: "3c912300775d1ad730dc35757e279c274c0acaad", size: 1048576, region: "USA", description: "" },
    { file: "panafz10e-anvil-norsa.bin", md5: "cf11bbb5a16d7af9875cca9de9a15e09", sha1: "2765c7b4557cc838b32567d2428d088980295159", size: 1048576, region: "World", description: "" },
    { file: "panafz10e-anvil.bin", md5: "a48e6746bd7edec0f40cff078f0bb19f", sha1: "a900371f0cdcdc03f79557f11d406fd71251a5fd", size: 1048576, region: "Europe", description: "" },
    { file: "panafz10ja-anvil-kanji.bin", md5: "428577250f43edc902ea239c50d2240d", sha1: "2e857b957803d0331fd229328df01f3ffab69eee", size: 1048576, region: "World", description: "" },
    { file: "panafz1j-kanji.bin", md5: "c23fb5d5e6bb1c240d02cf968972be37", sha1: "884515605ee243577ab20767ef8c1a7368e4e407", size: 1048576, region: "World", description: "" },
    { file: "panafz1j-norsa.bin", md5: "f6c71de7470d16abe4f71b1444883dc8", sha1: "a417587ae3b0b8ef00c830920c21af8bee88e419", size: 1048576, region: "World", description: "" },
    { file: "panafz1j.bin", md5: "a496cfdded3da562759be3561317b605", sha1: "ec7ec62d60ec0459a14ed56ebc66761ef3c80efc", size: 1048576, region: "World", description: "" },
    { file: "sanyotry.bin", md5: "35fa1a1ebaaeea286dc5cd15487c13ea", sha1: "b01c53da256dde43ffec4ad3fc3adfa8d635e943", size: 1048576, region: "Japan", description: "" },
    ],
  },
  "acpc": {
    required: false,
    files: [
    { file: "cpc_amsdos.rom", md5: "25629dfe870d097469c217b95fdc1c95", sha1: "39102c8e9cb55fcc0b9b62098780ed4a3cb6a4bb", size: 16384, region: "World", description: "" },
    { file: "cpc464.rom", md5: "a993f85b88ac4350cf4d41554e87fe4f", sha1: "56d39c463da60968d93e58b4ba0e675829412a20", size: 32768, region: "World", description: "" },
    { file: "cpc6128.rom", md5: "b96280dc6c95a48857b4b8eb931533ae", sha1: "5977adbad3f7c1e0e082cd02fe76a700d9860c30", size: 32768, region: "World", description: "" },
    { file: "cpc664.rom", md5: "5a384a2310f472c7857888371c00ed66", sha1: "073a7665527b5bd8a148747a3947dbd3328682c8", size: 32768, region: "World", description: "" },
    ],
  },
  "amiga": {
    required: true,
    files: [
    { file: "kick33180.A500", md5: "85ad74194e87c08904327de1a9443b7a", sha1: "11f9e62cf299f72184835b7b2a70a16333fc0d88", size: 262144, region: "World", description: "" },
    { file: "kick34005.A500", md5: "82a21c1890cae844b3df741f2762d48d", sha1: "891e9a547772fe0c6c19b610baf8bc4ea7fcb785", size: 262144, region: "World", description: "" },
    { file: "kick34005.CDTV", md5: "89da1838a24460e4b93f4f0c5d92d48d", sha1: "7ba40ffa17e500ed9fed041f3424bd81d9c907be", size: 262144, region: "World", description: "" },
    { file: "kick37175.A500", md5: "dc10d7bdd1b6f450773dfb558477c230", sha1: "c5839f5cb98a7a8947065c3ed2f14f5f42e334a1", size: 524288, region: "World", description: "" },
    { file: "kick37350.A600", md5: "465646c9b6729f77eea5314d1f057951", sha1: "02843c4253bbd29aba535b0aa3bd9a85034ecde4", size: 524288, region: "World", description: "" },
    { file: "kick39106.A1200", md5: "b7cc148386aa631136f510cd29e42fc3", sha1: "70033828182fffc7ed106e5373a8b89dda76faa5", size: 524288, region: "World", description: "" },
    { file: "kick39106.A4000", md5: "9b8bdd5a3fd32c2a5a6f5b1aefc799a5", sha1: "f0b4e9e29e12218c2d5bd7020e4e785297d91fd7", size: 524288, region: "World", description: "" },
    { file: "kick40060.CD32", md5: "5f8924d013dd57a89cf349f4cdedc6b1", sha1: "3525be8887f79b5929e017b42380a79edfee542d", size: 524288, region: "World", description: "" },
    { file: "kick40060.CD32.ext", md5: "bb72565701b1b6faece07d68ea5da639", sha1: "5bef3d628ce59cc02a66e6e4ae0da48f60e78f7f", size: 524288, region: "World", description: "" },
    { file: "kick40063.A600", md5: "e40a5dfb3d017ba8779faba30cbd1c8e", sha1: "3b7f1493b27e212830f989f26ca76c02049f09ca", size: 524288, region: "World", description: "" },
    { file: "kick40068.A1200", md5: "646773759326fbac3b2311fd8c8793ee", sha1: "e21545723fe8374e91342617604f1b3d703094f1", size: 524288, region: "World", description: "" },
    { file: "kick40068.A4000", md5: "9bdedde6a4f33555b4a270c8ca53297d", sha1: "5fe04842d04a489720f0f4bb0e46948199406f49", size: 524288, region: "World", description: "" },
    ],
  },
  "arcade": {
    required: false,
    files: [
    { file: "aes.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "bubsys.zip", md5: "f81298afd68a1a24a49a1a2d9f087964", sha1: "1c0ffcd308b0c8c6dbb74ad8b811a0767200d366", size: 7950, region: "World", description: "" },
    { file: "cchip.zip", md5: "df6f8a3d83c028a5cb9f2f2be60773f3", sha1: "364f2302a145a0fd6de767d7f8484badde1d1a6e", size: 2700, region: "World", description: "" },
    { file: "channelf.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "coleco.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "decocass.zip", md5: "b7e1189b341bf6a8e270017c096d21b0", sha1: "30b97b2670b79d0de41cba190324c504846c6fa1", size: 16107, region: "World", description: "" },
    { file: "fdsbios.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "isgsm.zip", md5: "4a56d56e2219c5e2b006b66a4263c01c", sha1: "f590ccf688b4c05fa1da5c5dd92c224545170c3b", size: 10207, region: "World", description: "" },
    { file: "midssio.zip", md5: "5904b0de768d1d506e766aa7e18994c1", sha1: "54275c9833e497f71f76ab239030cc386c863991", size: 163, region: "World", description: "" },
    { file: "msx.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "namcoc69.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "namcoc70.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "namcoc75.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "neocdz.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "neogeo.zip", md5: "00dad01abdbf8ea9e79ad2fe11bdb182", sha1: "deb62b0074b8cae4f162c257662136733cfc76ad", size: 1859335, region: "World", description: "" },
    { file: "ngp.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "nmk004.zip", md5: "bfacf1a68792d5348f93cf724d2f1dda", sha1: "489256f5e2001070d2ad94c90d255282c71ed274", size: 3556, region: "World", description: "" },
    { file: "pgm.zip", md5: "87cc944eef4c671aa2629a8ba48a08e0", sha1: "c0c001ec80fa860857000f4cfc9844a28498a355", size: 2094636, region: "World", description: "" },
    { file: "qsound.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "skns.zip", md5: "3f956c4e7008804cb47cbde49bd5b908", sha1: "4257bd14b541fafbd555cb98ba079a3416a45934", size: 924762, region: "World", description: "" },
    { file: "spec128.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "spec1282a.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "spectrum.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "ym2608.zip", md5: "79ae0d2bb1901b7e606b6dc339b79a97", sha1: "06fc753d015b43ca1787f4cfd9331b1674202e64", size: 7609, region: "World", description: "" },
    ],
  },
  "atari5200": {
    required: true,
    files: [
    { file: "5200.rom", md5: "281f20ea4320404ec820fb7ec0693b38", sha1: "6ad7a1e8c9fad486fbec9498cb48bf5bc3adc530", size: 2048, region: "World", description: "" },
    ],
  },
  "atari7800": {
    required: false,
    files: [
    { file: "7800 BIOS (E).rom", md5: "397bb566584be7b9764e7a68974c4263", sha1: "5a140136a16d1d83e4ff32a19409ca376a8df874", size: 16384, region: "World", description: "" },
    { file: "7800 BIOS (U).rom", md5: "0763f1ffb006ddbe32e52d497ee848ae", sha1: "d9d134bb6b36907c615a594cc7688f7bfcef5b43", size: 4096, region: "World", description: "" },
    ],
  },
  "atari800": {
    required: false,
    files: [
    { file: "ATARIBAS.ROM", md5: "0bac0c6a50104045d902df4503a4c30b", sha1: "3693c9cb9bf3b41bae1150f7a8264992468fc8c0", size: 8192, region: "World", description: "" },
    { file: "ATARIOSA.ROM", md5: "eb1f32f5d9f382db1bbfb8d7f9cb343a", sha1: "6dd53356159a129ed12367beb3b24a771d41adb0", size: 10240, region: "World", description: "" },
    { file: "ATARIOSB.ROM", md5: "a3e8d617c95d08031fe1b20d541434b2", sha1: "f1f0741b1d34fb4350cf7cb8ab3b6ea11cdd8174", size: 10240, region: "World", description: "" },
    { file: "ATARIXL.ROM", md5: "06daac977823773a3eea3422fd26a703", sha1: "ae4f523ba08b6fd59f3cae515a2b2410bbd98f55", size: 16384, region: "World", description: "" },
    { file: "BB01R4_OS.ROM", md5: "b7a2a04677d34f069eeb643d5238bf86", sha1: "decde89fbae90adb591ad2fc553d35f49030c129", size: 16384, region: "World", description: "" },
    { file: "XEGAME.ROM", md5: "d7eb37aec6960cba36bc500e0e5d00bc", sha1: "a107db7f16a1129cf9d933c9cf4f013b068c9e82", size: 8192, region: "World", description: "" },
    ],
  },
  "atarist": {
    required: true,
    files: [
    { file: "tos.img", md5: "c1c57ce48e8ee4135885cee9e63a68a2", sha1: "735793fdba07fe8d5295caa03484f6ef3de931f5", size: 196608, region: "World", description: "" },
    ],
  },
  "atomiswave": {
    required: true,
    files: [
    { file: "dc/airlbios.zip", md5: "7a11bfe0cc72886d032e386db68f890c", sha1: "f2a730530f4989ca0e8860aa4e455b6a5fe69e1d", size: 715730, region: "World", description: "" },
    { file: "dc/awbios.zip", md5: "85254fbe320ca82a768ec2c26bb08def", sha1: "7940c7bf29eee85a5b2fdec78750b19aa22895dc", size: 42296, region: "World", description: "" },
    { file: "dc/f355bios.zip", md5: "547f3d12aed389058ca06148f1cca0ed", sha1: "b6ff66dcb5547bd91760d239ddf428a655631c53", size: 1394278, region: "World", description: "" },
    { file: "dc/f355dlx.zip", md5: "1028615bcac4c31634a3364ce5c04044", sha1: "48d1712d1b1cdfeeeb43c6287c17b0b6309cfaab", size: 2328436, region: "World", description: "" },
    { file: "dc/hod2bios.zip", md5: "f4011d3116500354edf7302a90402711", sha1: "782c303cbdfab1027b04db74a63e27bdad5e0c53", size: 1479106, region: "World", description: "" },
    { file: "dc/naomi.zip", md5: "526eda1e2a7920c92c88178789d71d84", sha1: "c96711c01c0158f161791d6fbe75d88329e8ac0a", size: 9321533, region: "World", description: "" },
    { file: "dc/naomi2.zip", md5: "c50072cbab75673e1b1a6b94355e6fa8", sha1: "2962e338ccc9f66f29b409f73ca27aeee79633ac", size: 7022501, region: "World", description: "" },
    { file: "dc/segasp.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    ],
  },
  "channelf": {
    required: true,
    files: [
    { file: "sl31253.bin", md5: "ac9804d4c0e9d07e33472e3726ed15c3", sha1: "81193965a374d77b99b4743d317824b53c3e3c78", size: 1024, region: "World", description: "" },
    { file: "sl31254.bin", md5: "da98f4bb3242ab80d76629021bb27585", sha1: "8f70d1b74483ba3a37e86cf16c849d601a8c3d2c", size: 1024, region: "World", description: "" },
    { file: "sl90025.bin", md5: "95d339631d867c8f1d15a5f2ec26069d", sha1: "759e2ed31fbde4a2d8daf8b9f3e0dffebc90dae2", size: 1024, region: "World", description: "" },
    ],
  },
  "coleco": {
    required: true,
    files: [
    { file: "BIOS.col", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "bioscv.rom", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "coleco.rom", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "colecovision.rom", md5: "2c66f5911e5b42b8ebe113403548eee7", sha1: "45bedc4cbdeac66c7df59e9e599195c778d86a92", size: 8192, region: "World", description: "" },
    ],
  },
  "dos": {
    required: false,
    files: [
    { file: "CM32L_CONTROL.ROM", md5: "bfff32b6144c1d706109accb6e6b1113", sha1: "a439fbb390da38cada95a7cbb1d6ca199cd66ef8", size: 65536, region: "World", description: "" },
    { file: "CM32L_PCM.ROM", md5: "08cdcfa0ed93e9cb16afa76e6ac5f0a4", sha1: "289cc298ad532b702461bfc738009d9ebe8025ea", size: 1048576, region: "World", description: "" },
    { file: "MT32_CONTROL.ROM", md5: "5626206284b22c2734f3e9efefcd2675", sha1: "b083518fffb7f66b03c23b7eb4f868e62dc5a987", size: 65536, region: "World", description: "" },
    { file: "MT32_PCM.ROM", md5: "89e42e386e82e0cacb4a2704a03706ca", sha1: "f6b1eebc4b2d200ec6d3d21d51325d5b48c60252", size: 524288, region: "World", description: "" },
    ],
  },
  "dreamcast": {
    required: false,
    files: [
    { file: "dc/boot.bin", md5: "e10c53c2f8b90bab96ead2d368858623", sha1: "8951d1bb219ab2ff8583033d2119c899cc81f18c", size: 2097152, region: "World", description: "" },
    { file: "dc/dc_boot.bin", md5: "e10c53c2f8b90bab96ead2d368858623", sha1: "8951d1bb219ab2ff8583033d2119c899cc81f18c", size: 2097152, region: "World", description: "" },
    { file: "dc/flash.bin", md5: "0a93f7940c455905bea6e392dfde92a4", sha1: "94d44d7f9529ec1642ba3771ed3c5f756d5bc872", size: 131072, region: "World", description: "" },
    ],
  },
  "fds": {
    required: true,
    files: [
    { file: "disksys.rom", md5: "ca30b50f880eb660a320674ed365ef7a", sha1: "57fe1bdee955bb48d357e463ccbf129496930b62", size: 8192, region: "World", description: "" },
    { file: "gamegenie.nes", md5: "7f98d77d7a094ad7d069b74bd553ec98", sha1: "f430a0d752a9fa0c7032db8131f9090d18f71779", size: 24592, region: "World", description: "" },
    ],
  },
  "gamecube": {
    required: false,
    files: [
    { file: "dolphin-emu/Sys/GC/dsp_coef.bin", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "dolphin-emu/Sys/GC/dsp_rom.bin", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "dolphin-emu/Sys/GC/EUR/IPL.bin", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "dolphin-emu/Sys/GC/font_japanese.bin", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "dolphin-emu/Sys/GC/font_western.bin", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "dolphin-emu/Sys/GC/JAP/IPL.bin", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "dolphin-emu/Sys/GC/USA/IPL.bin", md5: "", sha1: "", size: 0, region: "USA", description: "" },
    { file: "gc-dvd-20010608.bin", md5: "561532ad496f644897952d2cef5bb431", sha1: "27872c201e87b06a19bf85d36c796ef383f8d52d", size: 131072, region: "World", description: "" },
    { file: "gc-dvd-20010831.bin", md5: "b953eb1a8fc9922b3f7051c1cdc451f1", sha1: "ae7233cae8f94749796e0b740d6021e3b00a8926", size: 131072, region: "World", description: "" },
    { file: "gc-dvd-20020402.bin", md5: "413154dd0e2c824c9b18b807fd03ec4e", sha1: "691e46213d8428befdf568157e670b971ab94e1d", size: 131072, region: "World", description: "" },
    { file: "gc-dvd-20020823.bin", md5: "c03f6bbaf644eb9b3ee261dbe199eb42", sha1: "2faaf92bcaffe675f54f7249d30f3791507e22ab", size: 131072, region: "World", description: "" },
    { file: "gc-ntsc-10.bin", md5: "fc924a7c879b661abc37cec4f018fdf3", sha1: "a1837968288253ed541f2b11440b68f5a9b33875", size: 2097152, region: "World", description: "" },
    { file: "gc-ntsc-11.bin", md5: "019e39822a9ca3029124f74dd4d55ac4", sha1: "239eacd86527ff9a75aeb7282da65797baeef010", size: 2097152, region: "World", description: "" },
    { file: "gc-ntsc-12.bin", md5: "b17148254a5799684c7d783206504926", sha1: "ef9194ab4804aa0aa8540d846caf291b28331165", size: 2097152, region: "World", description: "" },
    { file: "gc-pal-10.bin", md5: "0cdda509e2da83c85bfe423dd87346cc", sha1: "f27c63e5394e2fd1606f70df004c4fc2d6027700", size: 2097152, region: "Europe", description: "" },
    { file: "gc-pal-11.bin", md5: "339848a0b7c2124cf155276c1e79cbd0", sha1: "f3cd0c7c61cbcefa85e7de3aff4cfa50bc508714", size: 2097152, region: "Europe", description: "" },
    { file: "gc-pal-12.bin", md5: "db92574caab77a7ec99d4605fd6f2450", sha1: "80b8744ff5e43585392f55546bd03a673d11ef5f", size: 2097152, region: "Europe", description: "" },
    ],
  },
  "gb": {
    required: false,
    files: [
    { file: "dmg_boot.bin", md5: "32fbbd84168d3482956eb3c5051637f5", sha1: "4ed31ec6b0b175bb109c0eb5fd3d193da823339f", size: 256, region: "World", description: "" },
    { file: "gb_bios.bin", md5: "32fbbd84168d3482956eb3c5051637f5", sha1: "4ed31ec6b0b175bb109c0eb5fd3d193da823339f", size: 256, region: "World", description: "" },
    ],
  },
  "gba": {
    required: false,
    files: [
    { file: "gba_bios.bin", md5: "a860e8c0b6d573d191e4ec7db1b1e4f6", sha1: "300c20df6731a33952ded8c436f7f186d25d3492", size: 16384, region: "World", description: "" },
    ],
  },
  "gbc": {
    required: false,
    files: [
    { file: "cgb_boot.bin", md5: "dbfce9db9deaa2567f6a84fde55f9680", sha1: "1293d68bf9643bc4f36954c1e80e38f39864528d", size: 2304, region: "World", description: "" },
    { file: "gbc_bios.bin", md5: "dbfce9db9deaa2567f6a84fde55f9680", sha1: "1293d68bf9643bc4f36954c1e80e38f39864528d", size: 2304, region: "World", description: "" },
    ],
  },
  "gg": {
    required: false,
    files: [
    { file: "bios.gg", md5: "672e104c3be3a238301aceffc3b23fd6", sha1: "914aa165e3d879f060be77870d345b60cfeb4ede", size: 1024, region: "World", description: "" },
    ],
  },
  "intellivision": {
    required: true,
    files: [
    { file: "exec.bin", md5: "62e761035cb657903761800f4437b8af", sha1: "5a65b922b562cb1f57dab51b73151283f0e20c7a", size: 8192, region: "World", description: "" },
    { file: "grom.bin", md5: "0cd5946c6473e42e8e4c2137785e427f", sha1: "f9608bb4ad1cfe3640d02844c7ad8e0bcd974917", size: 2048, region: "World", description: "" },
    ],
  },
  "lynx": {
    required: false,
    files: [
    { file: "lynxboot.img", md5: "fcd403db69f54290b51035d82f835e7b", sha1: "e4ed47fae31693e016b081c6bda48da5b70d7ccb", size: 512, region: "World", description: "" },
    ],
  },
  "mark3": {
    required: false,
    files: [
    { file: "bios_E.sms", md5: "840481177270d5642a14ca71ee72844c", sha1: "c315672807d8ddb8d91443729405c766dd95cae7", size: 8192, region: "World", description: "" },
    { file: "bios_J.sms", md5: "24a519c53f67b00640d0048ef7089105", sha1: "a8c1b39a2e41137835eda6a5de6d46dd9fadbaf2", size: 8192, region: "World", description: "" },
    { file: "bios_U.sms", md5: "840481177270d5642a14ca71ee72844c", sha1: "c315672807d8ddb8d91443729405c766dd95cae7", size: 8192, region: "World", description: "" },
    { file: "bios.sms", md5: "840481177270d5642a14ca71ee72844c", sha1: "c315672807d8ddb8d91443729405c766dd95cae7", size: 8192, region: "World", description: "" },
    ],
  },
  "megacd": {
    required: true,
    files: [
    { file: "bios_CD_E.bin", md5: "e66fa1dc5820d254611fdcdba0662372", sha1: "f891e0ea651e2232af0c5c4cb46a0cae2ee8f356", size: 131072, region: "Europe", description: "" },
    { file: "bios_CD_J.bin", md5: "278a9397d192149e84e820ac621a8edd", sha1: "4846f448160059a7da0215a5df12ca160f26dd69", size: 131072, region: "Japan", description: "" },
    { file: "bios_CD_U.bin", md5: "2efd74e3232ff260e371b99f84024f7f", sha1: "f4f315adcef9b8feb0364c21ab7f0eaf5457f3ed", size: 131072, region: "USA", description: "" },
    ],
  },
  "msx": {
    required: true,
    files: [
    { file: "CARTS.SHA", md5: "74b0f217fa0e2b8bb5a2f8e2ecc69da3", sha1: "bf5fb954db868e523febccc68549ed9187961076", size: 33152, region: "World", description: "" },
    { file: "CYRILLIC.FNT", md5: "85b38e4128bbc300e675f55b278683a8", sha1: "000ac11b702a4c42e40f135df12fa5f2f13e20a1", size: 2048, region: "World", description: "" },
    { file: "DISK.ROM", md5: "80dcd1ad1a4cf65d64b7ba10504e8190", sha1: "032cb1c1c75b9a191fa1230978971698d9d2a17f", size: 16384, region: "World", description: "" },
    { file: "FMPAC.ROM", md5: "6f69cc8b5ed761b03afd78000dfb0e19", sha1: "9d789166e3caf28e4742fe933d962e99618c633d", size: 65536, region: "World", description: "" },
    { file: "FMPAC16.ROM", md5: "af8537262df8df267072f359399a7635", sha1: "2dc4517ebd5a061f9b5aa6b449cc4d4a2073540c", size: 16384, region: "World", description: "" },
    { file: "ITALIC.FNT", md5: "c83e50e9f33b8dd893c414691822740d", sha1: "401dd6692dc80628e5f68b7c79be0b0ebbc4d3ee", size: 2048, region: "World", description: "" },
    { file: "KANJI.ROM", md5: "febe8782b466d7c3b16de6d104826b34", sha1: "84a645becec0a25d3ab7a909cde1b242699a8662", size: 131072, region: "World", description: "" },
    { file: "MSX.ROM", md5: "aa95aea2563cd5ec0a0919b44cc17d47", sha1: "409e82adac40f6bdd18eb6c84e8b2fbdc7fb5498", size: 32768, region: "World", description: "" },
    { file: "MSX2.ROM", md5: "ec3a01c91f24fbddcbcab0ad301bc9ef", sha1: "6103b39f1e38d1aa2d84b1c3219c44f1abb5436e", size: 32768, region: "World", description: "" },
    { file: "MSX2EXT.ROM", md5: "2183c2aff17cf4297bdb496de78c2e8a", sha1: "5c1f9c7fb655e43d38e5dd1fcc6b942b2ff68b02", size: 16384, region: "World", description: "" },
    { file: "MSX2P.ROM", md5: "6d8c0ca64e726c82a4b726e9b01cdf1e", sha1: "e2fbd56e42da637609d23ae9df9efd1b4241b18a", size: 32768, region: "World", description: "" },
    { file: "MSX2PEXT.ROM", md5: "7c8243c71d8f143b2531f01afa6a05dc", sha1: "fe0254cbfc11405b79e7c86c7769bd6322b04995", size: 16384, region: "World", description: "" },
    { file: "MSXDOS2.ROM", md5: "6418d091cd6907bbcf940324339e43bb", sha1: "c36c9e0f96738a340381e23b4f97245388801a46", size: 65536, region: "World", description: "" },
    { file: "PAINTER.ROM", md5: "403cdea1cbd2bb24fae506941f8f655e", sha1: "7fd2a28c4fdaeb140f3c8c8fb90271b1472c97b9", size: 65536, region: "World", description: "" },
    { file: "RS232.ROM", md5: "279efd1eae0d358eecd4edc7d9adedf3", sha1: "7aec0134ad6a5177f4056fcb6047083e8e00529b", size: 16640, region: "World", description: "" },
    ],
  },
  "msx2": {
    required: true,
    files: [
    { file: "CARTS.SHA", md5: "74b0f217fa0e2b8bb5a2f8e2ecc69da3", sha1: "bf5fb954db868e523febccc68549ed9187961076", size: 33152, region: "World", description: "" },
    { file: "CYRILLIC.FNT", md5: "85b38e4128bbc300e675f55b278683a8", sha1: "000ac11b702a4c42e40f135df12fa5f2f13e20a1", size: 2048, region: "World", description: "" },
    { file: "DISK.ROM", md5: "80dcd1ad1a4cf65d64b7ba10504e8190", sha1: "032cb1c1c75b9a191fa1230978971698d9d2a17f", size: 16384, region: "World", description: "" },
    { file: "FMPAC.ROM", md5: "6f69cc8b5ed761b03afd78000dfb0e19", sha1: "9d789166e3caf28e4742fe933d962e99618c633d", size: 65536, region: "World", description: "" },
    { file: "FMPAC16.ROM", md5: "af8537262df8df267072f359399a7635", sha1: "2dc4517ebd5a061f9b5aa6b449cc4d4a2073540c", size: 16384, region: "World", description: "" },
    { file: "ITALIC.FNT", md5: "c83e50e9f33b8dd893c414691822740d", sha1: "401dd6692dc80628e5f68b7c79be0b0ebbc4d3ee", size: 2048, region: "World", description: "" },
    { file: "KANJI.ROM", md5: "febe8782b466d7c3b16de6d104826b34", sha1: "84a645becec0a25d3ab7a909cde1b242699a8662", size: 131072, region: "World", description: "" },
    { file: "MSX.ROM", md5: "aa95aea2563cd5ec0a0919b44cc17d47", sha1: "409e82adac40f6bdd18eb6c84e8b2fbdc7fb5498", size: 32768, region: "World", description: "" },
    { file: "MSX2.ROM", md5: "ec3a01c91f24fbddcbcab0ad301bc9ef", sha1: "6103b39f1e38d1aa2d84b1c3219c44f1abb5436e", size: 32768, region: "World", description: "" },
    { file: "MSX2EXT.ROM", md5: "2183c2aff17cf4297bdb496de78c2e8a", sha1: "5c1f9c7fb655e43d38e5dd1fcc6b942b2ff68b02", size: 16384, region: "World", description: "" },
    { file: "MSX2P.ROM", md5: "6d8c0ca64e726c82a4b726e9b01cdf1e", sha1: "e2fbd56e42da637609d23ae9df9efd1b4241b18a", size: 32768, region: "World", description: "" },
    { file: "MSX2PEXT.ROM", md5: "7c8243c71d8f143b2531f01afa6a05dc", sha1: "fe0254cbfc11405b79e7c86c7769bd6322b04995", size: 16384, region: "World", description: "" },
    { file: "MSXDOS2.ROM", md5: "6418d091cd6907bbcf940324339e43bb", sha1: "c36c9e0f96738a340381e23b4f97245388801a46", size: 65536, region: "World", description: "" },
    { file: "PAINTER.ROM", md5: "403cdea1cbd2bb24fae506941f8f655e", sha1: "7fd2a28c4fdaeb140f3c8c8fb90271b1472c97b9", size: 65536, region: "World", description: "" },
    { file: "RS232.ROM", md5: "279efd1eae0d358eecd4edc7d9adedf3", sha1: "7aec0134ad6a5177f4056fcb6047083e8e00529b", size: 16640, region: "World", description: "" },
    ],
  },
  "n64dd": {
    required: true,
    files: [
    { file: "64DD_IPL.bin", md5: "8d3d9f294b6e174bc7b1d2fd1c727530", sha1: "bf861922dcb78c316360e3e742f4f70ff63c9bc3", size: 4194304, region: "World", description: "" },
    ],
  },
  "naomi": {
    required: true,
    files: [
    { file: "dc/airlbios.zip", md5: "7a11bfe0cc72886d032e386db68f890c", sha1: "f2a730530f4989ca0e8860aa4e455b6a5fe69e1d", size: 715730, region: "World", description: "" },
    { file: "dc/awbios.zip", md5: "85254fbe320ca82a768ec2c26bb08def", sha1: "7940c7bf29eee85a5b2fdec78750b19aa22895dc", size: 42296, region: "World", description: "" },
    { file: "dc/f355bios.zip", md5: "547f3d12aed389058ca06148f1cca0ed", sha1: "b6ff66dcb5547bd91760d239ddf428a655631c53", size: 1394278, region: "World", description: "" },
    { file: "dc/f355dlx.zip", md5: "1028615bcac4c31634a3364ce5c04044", sha1: "48d1712d1b1cdfeeeb43c6287c17b0b6309cfaab", size: 2328436, region: "World", description: "" },
    { file: "dc/hod2bios.zip", md5: "f4011d3116500354edf7302a90402711", sha1: "782c303cbdfab1027b04db74a63e27bdad5e0c53", size: 1479106, region: "World", description: "" },
    { file: "dc/naomi.zip", md5: "526eda1e2a7920c92c88178789d71d84", sha1: "c96711c01c0158f161791d6fbe75d88329e8ac0a", size: 9321533, region: "World", description: "" },
    { file: "dc/naomi2.zip", md5: "c50072cbab75673e1b1a6b94355e6fa8", sha1: "2962e338ccc9f66f29b409f73ca27aeee79633ac", size: 7022501, region: "World", description: "" },
    { file: "dc/segasp.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    ],
  },
  "nds": {
    required: false,
    files: [
    { file: "bios7.bin", md5: "df692a80a5b1bc90728bc3dfc76cd948", sha1: "24f67bdea115a2c847c8813a262502ee1607b7df", size: 16384, region: "World", description: "" },
    { file: "bios9.bin", md5: "a392174eb3e572fed6447e956bde4b25", sha1: "bfaac75f101c135e32e2aaf541de6b1be4c8c62d", size: 4096, region: "World", description: "" },
    { file: "dsi_bios7.bin", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "dsi_bios9.bin", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "dsi_firmware.bin", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "dsi_nand.bin", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "firmware.bin", md5: "e45033d9b0fa6b0de071292bba7c9d13", sha1: "cfe072921ee3fb93f688743f8beef89043c3e9ad", size: 262144, region: "World", description: "" },
    ],
  },
  "neogeo": {
    required: true,
    files: [
    { file: "aes.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "bubsys.zip", md5: "f81298afd68a1a24a49a1a2d9f087964", sha1: "1c0ffcd308b0c8c6dbb74ad8b811a0767200d366", size: 7950, region: "World", description: "" },
    { file: "cchip.zip", md5: "df6f8a3d83c028a5cb9f2f2be60773f3", sha1: "364f2302a145a0fd6de767d7f8484badde1d1a6e", size: 2700, region: "World", description: "" },
    { file: "channelf.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "coleco.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "decocass.zip", md5: "b7e1189b341bf6a8e270017c096d21b0", sha1: "30b97b2670b79d0de41cba190324c504846c6fa1", size: 16107, region: "World", description: "" },
    { file: "fdsbios.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "isgsm.zip", md5: "4a56d56e2219c5e2b006b66a4263c01c", sha1: "f590ccf688b4c05fa1da5c5dd92c224545170c3b", size: 10207, region: "World", description: "" },
    { file: "midssio.zip", md5: "5904b0de768d1d506e766aa7e18994c1", sha1: "54275c9833e497f71f76ab239030cc386c863991", size: 163, region: "World", description: "" },
    { file: "msx.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "namcoc69.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "namcoc70.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "namcoc75.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "neocdz.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "neogeo.zip", md5: "00dad01abdbf8ea9e79ad2fe11bdb182", sha1: "deb62b0074b8cae4f162c257662136733cfc76ad", size: 1859335, region: "World", description: "" },
    { file: "ngp.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "nmk004.zip", md5: "bfacf1a68792d5348f93cf724d2f1dda", sha1: "489256f5e2001070d2ad94c90d255282c71ed274", size: 3556, region: "World", description: "" },
    { file: "pgm.zip", md5: "87cc944eef4c671aa2629a8ba48a08e0", sha1: "c0c001ec80fa860857000f4cfc9844a28498a355", size: 2094636, region: "World", description: "" },
    { file: "qsound.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "skns.zip", md5: "3f956c4e7008804cb47cbde49bd5b908", sha1: "4257bd14b541fafbd555cb98ba079a3416a45934", size: 924762, region: "World", description: "" },
    { file: "spec128.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "spec1282a.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "spectrum.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "ym2608.zip", md5: "79ae0d2bb1901b7e606b6dc339b79a97", sha1: "06fc753d015b43ca1787f4cfd9331b1674202e64", size: 7609, region: "World", description: "" },
    ],
  },
  "neogeocd": {
    required: true,
    files: [
    { file: "000-lo.lo", md5: "fc7599f3f871578fe9a0453662d1c966", sha1: "5992277debadeb64d1c1c64b0a92d9293eaf7e4a", size: 131072, region: "World", description: "" },
    { file: "front-sp1.bin", md5: "5c2366f25ff92d71788468ca492ebeca", sha1: "53bc1f283cdf00fa2efbb79f2e36d4c8038d743a", size: 524288, region: "World", description: "" },
    { file: "neocd_f.rom", md5: "8834880c33164ccbe6476b559f3e37de", sha1: "a5f4a7a627b3083c979f6ebe1fabc5d2df6d083b", size: 524288, region: "Europe", description: "" },
    { file: "neocd_sf.rom", md5: "043d76d5f0ef836500700c34faef774d", sha1: "4a94719ee5d0e3f2b981498f70efc1b8f1cef325", size: 524288, region: "Japan", description: "" },
    { file: "neocd_st.rom", md5: "f6325a33c6d63ea4b9162a3fa8c32727", sha1: "19729b51bdab60c42aafef6e20ea9234c7eb8410", size: 524288, region: "World", description: "" },
    { file: "neocd_sz.rom", md5: "971ee8a36fb72da57aed01758f0a37f5", sha1: "6a947457031dd3a702a296862446d7485aa89dbb", size: 524288, region: "World", description: "" },
    { file: "neocd_t.rom", md5: "de3cf45d227ad44645b22aa83b49f450", sha1: "cc92b54a18a8bff6e595aabe8e5c360ba9e62eb5", size: 524288, region: "World", description: "" },
    { file: "neocd_z.rom", md5: "11526d58d4c524daef7d5d677dc6b004", sha1: "b0f1c4fa8d4492a04431805f6537138b842b549f", size: 524288, region: "USA", description: "" },
    { file: "neocd.bin", md5: "f39572af7584cb5b3f70ae8cc848aba2", sha1: "7bb26d1e5d1e930515219cb18bcde5b7b23e2eda", size: 524288, region: "World", description: "" },
    { file: "top-sp1.bin", md5: "122aee210324c72e8a11116e6ef9c0d0", sha1: "235f4d1d74364415910f73c10ae5482d90b4274f", size: 524288, region: "World", description: "" },
    { file: "uni-bioscd.rom", md5: "08ca8b2dba6662e8024f9e789711c6fc", sha1: "5142f205912869b673a71480c5828b1eaed782a8", size: 524288, region: "World", description: "" },
    ],
  },
  "nes": {
    required: false,
    files: [
    { file: "NstDatabase.xml", md5: "7bfe8c0540ed4bd6a0f1e2a0f0118ced", sha1: "26322f182540211e9b5e3647675b7c593706ae2b", size: 1009534, region: "World", description: "" },
    ],
  },
  "odyssey2": {
    required: true,
    files: [
    { file: "c52.bin", md5: "f1071cdb0b6b10dde94d3bc8a6146387", sha1: "a6120aed50831c9c0d95dbdf707820f601d9452e", size: 1024, region: "World", description: "" },
    { file: "g7400.bin", md5: "c500ff71236068e0dc0d0603d265ae76", sha1: "5130243429b40b01a14e1304d0394b8459a6fbae", size: 1024, region: "World", description: "" },
    { file: "jopac.bin", md5: "279008e4a0db2dc5f1c048853b033828", sha1: "54b8d2c1317628de51a85fc1c424423a986775e4", size: 1024, region: "World", description: "" },
    { file: "o2rom.bin", md5: "562d5ebf9e030a40d6fabfc2f33139fd", sha1: "b2e1955d957a475de2411770452eff4ea19f4cee", size: 1024, region: "World", description: "" },
    ],
  },
  "pcecd": {
    required: true,
    files: [
    { file: "gecard.pce", md5: "6d2cb14fc3e1f65ceb135633d1694122", sha1: "014881a959e045e00f4db8f52955200865d40280", size: 32768, region: "World", description: "" },
    { file: "gexpress.pce", md5: "6d2cb14fc3e1f65ceb135633d1694122", sha1: "014881a959e045e00f4db8f52955200865d40280", size: 32768, region: "World", description: "" },
    { file: "syscard1.pce", md5: "2b7ccb3d86baa18f6402c176f3065082", sha1: "a39a66da7de6ba94ab84d04eef7afeec7d4ee66a", size: 262144, region: "World", description: "" },
    { file: "syscard2.pce", md5: "3cdd6614a918616bfc41c862e889dd79", sha1: "88da02e2503f7c32810f5d93a34849d470742b6d", size: 262144, region: "World", description: "" },
    { file: "syscard2u.pce", md5: "94279f315e8b52904f65ab3108542afe", sha1: "2bea3dac98f84b2f2f469fa77ea720b8770d598d", size: 262144, region: "World", description: "" },
    { file: "syscard3.pce", md5: "38179df8f4ac870017db21ebcbf53114", sha1: "79f5ff55dd10187c7fd7b8daab0b3ffbd1f56a2c", size: 262144, region: "World", description: "" },
    { file: "syscard3u.pce", md5: "0754f903b52e3b3342202bdafb13efa5", sha1: "d02611d99921986147c753df14c7349b31d71950", size: 262144, region: "World", description: "" },
    ],
  },
  "pcenginecd": {
    required: true,
    files: [
    { file: "gecard.pce", md5: "6d2cb14fc3e1f65ceb135633d1694122", sha1: "014881a959e045e00f4db8f52955200865d40280", size: 32768, region: "World", description: "" },
    { file: "gexpress.pce", md5: "6d2cb14fc3e1f65ceb135633d1694122", sha1: "014881a959e045e00f4db8f52955200865d40280", size: 32768, region: "World", description: "" },
    { file: "syscard1.pce", md5: "2b7ccb3d86baa18f6402c176f3065082", sha1: "a39a66da7de6ba94ab84d04eef7afeec7d4ee66a", size: 262144, region: "World", description: "" },
    { file: "syscard2.pce", md5: "3cdd6614a918616bfc41c862e889dd79", sha1: "88da02e2503f7c32810f5d93a34849d470742b6d", size: 262144, region: "World", description: "" },
    { file: "syscard2u.pce", md5: "94279f315e8b52904f65ab3108542afe", sha1: "2bea3dac98f84b2f2f469fa77ea720b8770d598d", size: 262144, region: "World", description: "" },
    { file: "syscard3.pce", md5: "38179df8f4ac870017db21ebcbf53114", sha1: "79f5ff55dd10187c7fd7b8daab0b3ffbd1f56a2c", size: 262144, region: "World", description: "" },
    { file: "syscard3u.pce", md5: "0754f903b52e3b3342202bdafb13efa5", sha1: "d02611d99921986147c753df14c7349b31d71950", size: 262144, region: "World", description: "" },
    ],
  },
  "pcfx": {
    required: true,
    files: [
    { file: "fx-scsi.rom", md5: "430e9745f9235c515bc8e652d6ca3004", sha1: "65482a23ac5c10a6095aee1db5824cca54ead6e5", size: 524288, region: "World", description: "" },
    { file: "pcfx.rom", md5: "08e36edbea28a017f79f8d4f7ff9b6d7", sha1: "1a77fd83e337f906aecab27a1604db064cf10074", size: 1048576, region: "World", description: "" },
    { file: "pcfxbios.bin", md5: "08e36edbea28a017f79f8d4f7ff9b6d7", sha1: "1a77fd83e337f906aecab27a1604db064cf10074", size: 1048576, region: "World", description: "" },
    { file: "pcfxga.rom", md5: "5885bc9a64bf80d4530b9b9b978ff587", sha1: "a9372202a5db302064c994fcda9b24d29bb1b41c", size: 1048576, region: "World", description: "" },
    { file: "pcfxv101.bin", md5: "e2fb7c7220e3a7838c2dd7e401a7f3d8", sha1: "8b662f7548078be52a871565e19511ccca28c5c8", size: 1048576, region: "World", description: "" },
    ],
  },
  "ps2": {
    required: true,
    files: [
    { file: "pcsx2/bios/ps2-0100j-20000117.bin", md5: "acf4730ceb38ac9d8c7d8e21f2614600", sha1: "aea061e6e263fdcc1c4fdbd68553ef78dae74263", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0100jd-20000117.bin", md5: "32f2e4d5ff5ee11072a6bc45530f5765", sha1: "5b33170323ed6344e2363fed8115dc3918bb96a4", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0101j-20000217.bin", md5: "b1459d7446c69e3e97e6ace3ae23dd1c", sha1: "916e02431bcd73140504da3355c9598143b77e11", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0101jd-20000217.bin", md5: "acf9968c8f596d2b15f42272082513d1", sha1: "16f4a284d0e760ee13a2aff2f7dda928255e3080", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0101xd-20000224.bin", md5: "d3f1853a16c2ec18f3cd1ae655213308", sha1: "4440b246bfde7bb31002c584a76c6ef384908e84", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0110a-20000727.bin", md5: "a20c97c02210f16678ca3010127caf36", sha1: "20f6ce6693cf97e9494f8f0227f2b7988ffaf961", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0110ad-20000727.bin", md5: "63e6fd9b3c72e0d7b920e80cf76645cd", sha1: "339c646cf0699268552df5b05f18f0a03a9f55ff", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0120a-20000902.bin", md5: "8db2fbbac7413bf3e7154c1e0715e565", sha1: "dbc2318a1029347b5af3a0c74b0bdf88d19efee6", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0120e-20000902.bin", md5: "b7fa11e87d51752a98b38e3e691cbf17", sha1: "274c05fec654913a3f698d4b0d592085866a2cbd", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0120ed-20000902-20030110.bin", md5: "3016b3dd42148a67e2c048595ca4d7ce", sha1: "1b73dec999fcc2b92fa958110ff6bfe4d0af276e", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0120ed-20000902.bin", md5: "91c87cb2f2eb6ce529a2360f80ce2457", sha1: "3bb1eecd618ab5c973c7bc53671a4475a02e1d5b", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0120j-20001027-185015.bin", md5: "f63bc530bd7ad7c026fcd6f7bd0d9525", sha1: "e481079eca752225555f0c26d14c9d0f94d9a8e9", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0120j-20001027-191435.bin", md5: "cee06bd68c333fc5768244eae77e4495", sha1: "a9f5d8ed56cfff18add1b599010493461fa02448", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0150a-20001228.bin", md5: "8accc3c49ac45f5ae2c5db0adc854633", sha1: "5af5b5077d84a9c037ebe12bfab8a38b31d8a543", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0150ad-20001228-20030520.bin", md5: "0bf988e9c7aaa4c051805b0fa6eb3387", sha1: "7284b9d16df9935afc384318e024c87ef0574fe5", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0150e-20001228.bin", md5: "838544f12de9b0abc90811279ee223c8", sha1: "e22ef231faf3661edd92f2ee449a71297c82a092", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0150ed-20001228-20030520.bin", md5: "6f9a6feb749f0533aaae2cc45090b0ed", sha1: "d004326c9d8060812b4433c3f07646b04854d6c4", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0150j-20010118.bin", md5: "815ac991d8bc3b364696bead3457de7d", sha1: "d6f365a0f07cd04ed28108e6ec5076e2f81e5f72", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0150jd-20010118.bin", md5: "bb6bbc850458fff08af30e969ffd0175", sha1: "334e029fc7fd50222a399c50384ff42732652259", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0160a-20010427.bin", md5: "b107b5710042abe887c0f6175f6e94bb", sha1: "7331a40b4b4feb1b3f0f77b013b6d38483577baa", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0160a-20010704.bin", md5: "18bcaadb9ff74ed3add26cdf709fff2e", sha1: "ce92e8e8c88665f2f645a9522e337823d47a914a", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0160a-20011004.bin", md5: "7200a03d51cacc4c14fcdfdbc4898431", sha1: "d257bce6ecaf3bafb704c75a1b4741b910bd2d49", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0160a-20020207.bin", md5: "d5ce2c7d119f563ce04bc04dbc3a323e", sha1: "f9a5d629a036b99128f7cb530c6e3ca016e9c8b7", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0160e-20010704.bin", md5: "491209dd815ceee9de02dbbc408c06d6", sha1: "3cbd048e437c785b5a05a0feced00117a8a42545", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0160e-20011004.bin", md5: "8359638e857c8bc18c3c18ac17d9cc3c", sha1: "ee34c3a87c53c75ca2a37d77b0042ca24d07831f", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0160e-20020319.bin", md5: "0d2228e6fd4fb639c9c39d077a9ec10c", sha1: "bff2902bd0ce9729a060581132541e9fd1a9fab6", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0160e-20020426.bin", md5: "5b1f47fbeb277c6be2fccdd6344ff2fd", sha1: "d106b757ae2544dfe63f7e1924e59d5ad44c0c29", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0160h-20010730.bin", md5: "352d2ff9b3f68be7e6fa7e6dd8389346", sha1: "ba15dcf7aac13864c08222037e9321d7468c87d1", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0160h-20020426.bin", md5: "315a4003535dfda689752cb25f24785c", sha1: "e3a74125c426bcacabca00b513fab928665c8846", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0160j-20010427.bin", md5: "ab55cceea548303c22c72570cfd4dd71", sha1: "e525a0c900e37acf0ae5a655d82a0abcb07c6f1f", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0160j-20020426.bin", md5: "72da56fccb8fcd77bba16d1b6f479914", sha1: "003628c137dae577ff3b04b93ca1787b0c944702", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0170a-20030325.bin", md5: "8aa12ce243210128c5074552d3b86251", sha1: "d269d1ed513227f3ef7133c76cf1b3a64f97b15d", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0170ad-20030325.bin", md5: "eb960de68f0c0f7f9fa083e9f79d0360", sha1: "c5bc6e893b4c43d528142e56c96073024de64157", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0170e-20030227.bin", md5: "6e69920fa6eef8522a1d688a11e41bc6", sha1: "ad15bd7eabd5bd81ba011516a5be44947d6641aa", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0170ed-20030227.bin", md5: "666018ffec65c5c7e04796081295c6c7", sha1: "e220bb282378c1f48ea1b585b3675e51a6dca572", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0170j-20030206.bin", md5: "312ad4816c232a9606e56f946bc0678a", sha1: "d812ac65c357d392396ca9edee812dc41bed8bde", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0180cd-20030224.bin", md5: "240d4c5ddd4b54069bdc4a3cd2faf99d", sha1: "2de87767008fc4a303af64a46251156e965d9065", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0180j-20031028.bin", md5: "1c6cd089e6c83da618fbf2a081eb4888", sha1: "aa4a35c14ee342cf7a03b1dde294ca10e64889e1", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0190a-20030623.bin", md5: "35461cecaa51712b300b2d6798825048", sha1: "c74d92a2952a2912b6698cbcf7742adac8f784d3", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0190a-20040329.bin", md5: "81f4336c1de607dd0865011c0447052e", sha1: "b68c05f5cd86bf03cb38a643a723b7a97b759531", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0190c-20030623.bin", md5: "1b6e631b536247756287b916f9396872", sha1: "92d9eb4b11cef97bb69a275b2851b72f7b0023d6", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0190e-20030623.bin", md5: "bd6415094e1ce9e05daabe85de807666", sha1: "18b9ba833c469c4683676cc20da5124080d980bb", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0190e-20030822.bin", md5: "afde410bd026c16be605a1ae4bd651fd", sha1: "6e1f0eb4aec51a6288b3d802d3bcdb477cf52104", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0190h-20030623.bin", md5: "2e70ad008d4ec8549aada8002fdf42fb", sha1: "caa18ed04854a91e68f2d61a782560edd6373bbf", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0190j-20030623.bin", md5: "463d87789c555a4a7604e97d7db545d1", sha1: "6a6ecfe6c10e42eff1ca056349def799b5629067", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0190j-20030822.bin", md5: "00da1b177096cfd2532c8fa22b43e667", sha1: "0ea98a25a32145dda514de2f0d4bfbbd806bd00c", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0190r-20030623.bin", md5: "b53d51edc7fc086685e31b811dc32aad", sha1: "34a81db03ab617fbfdd7f9b861692dd2ecd57b82", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0200a-20040614.bin", md5: "d333558cc14561c1fdc334c75d5f37b7", sha1: "7a62e5f48603582707e9898eb055ea3eaee50d4c", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0200e-20040614.bin", md5: "dc752f160044f2ed5fc1f4964db2a095", sha1: "434bc0b4eb4827da0773ec0795aadc5162569a07", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0200ed-20040614.bin", md5: "63ead1d74893bf7f36880af81f68a82d", sha1: "902f4680b258abd40c0922f6b0d581cbd8f8a73e", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0200h-20040614.bin", md5: "3e3e030c0f600442fa05b94f87a1e238", sha1: "7f8e812cab7c7393c85eac6c42661e1fd0a642df", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0200j-20040614.bin", md5: "0eee5d1c779aa50e94edd168b4ebf42e", sha1: "224ab5704ab719edeb05ca1d835812252c97c1b3", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0210j-20040917.bin", md5: "1ad977bb539fc9448a08ab276a836bbc", sha1: "bbb1af3085e77599691ec430d147810157da934f", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0220a-20050620.bin", md5: "929a14baca1776b00869f983aa6e14d2", sha1: "48d0445dffd1e879c7ae752c5166ec3101921555", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0220a-20060210.bin", md5: "cb801b7920a7d536ba07b6534d2433ca", sha1: "92e488d5b2705e4cca83d4d1efbc421012faf83e", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0220a-20060905.bin", md5: "40c11c063b3b9409aa5e4058e984e30c", sha1: "8361d615cc895962e0f0838489337574dbdc9173", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0220ad-20050620.bin", md5: "9959ad7a8685cad66206e7752ca23f8b", sha1: "7c7efdfcec7705f4e84bb47f45322104e39eed09", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0220ad-20060905.bin", md5: "21fe4cad111f7dc0f9af29477057f88d", sha1: "4191b5842f31a9985b5428bc9d2b733ce3abb583", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0220e-20050620.bin", md5: "573f7d4a430c32b3cc0fd0c41e104bbd", sha1: "929a85e974faf4b40d0a7785023b758402c43bd9", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0220e-20060210.bin", md5: "af60e6d1a939019d55e5b330d24b1c25", sha1: "28ad756d0cfd1e7b2e2de3de5d9e14207ee89761", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0220e-20060905.bin", md5: "80bbb237a6af9c611df43b16b930b683", sha1: "da5aacead2fb55807d6d4e70b1f10f4fdcfd3281", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0220h-20050620.bin", md5: "df63a604e8bff5b0599bd1a6c2721bd0", sha1: "0a071d1b46607a7694770407606d8599f62a372b", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0220h-20060210.bin", md5: "549a66d0c698635ca9fa3ab012da7129", sha1: "fce2a24e5e0400cc6d98c08f426405d19173813e", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0220h-20060905.bin", md5: "c37bce95d32b2be480f87dd32704e664", sha1: "a5a2ee0dd9a86ca35b94e97ca92476a584f755bf", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0220j-20050620.bin", md5: "eb4f40fcf4911ede39c1bbfe91e7a89a", sha1: "7ffa75d142cb8eeea6c777dbcf263143655275d5", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0220j-20060210.bin", md5: "5b1ba4bb914406fae75ab8e38901684d", sha1: "0edf1fbb772a8e6a79ae00e977450e3ade25c4f3", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0220j-20060905.bin", md5: "5de9d0d730ff1e7ad122806335332524", sha1: "3baf847c1c217aa71ac6d298389c88edb3db32e2", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0230a-20080220.bin", md5: "21038400dc633070a78ad53090c53017", sha1: "f9229fe159d0353b9f0632f3fdc66819c9030458", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0230e-20080220.bin", md5: "dc69f0643a3030aaa4797501b483d6c4", sha1: "9915b5ba56798f4027ac1bd8d10abe0c1c9c326a", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0230h-20080220.bin", md5: "30d56e79d89fbddf10938fa67fe3f34e", sha1: "a277b456849697abec11285c6b35bc734598c220", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0230j-20080220.bin", md5: "80ac46fa7e77b8ab4366e86948e54f83", sha1: "fbd54bfc020af34008b317dcb80b812dd29b3759", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0250e-20100415.bin", md5: "93ea3bcee4252627919175ff1b16a1d9", sha1: "b9cb5775af29cd4d1ec5521e8231f8b6636e2e44", size: 4194304, region: "World", description: "" },
    { file: "pcsx2/bios/ps2-0250j-20100415.bin", md5: "d3e81e95db25f5a86a7b7474550a2155", sha1: "4b5ef16b67e3b523d28ed2406106cb80470a06d0", size: 4194304, region: "World", description: "" },
    ],
  },
  "psp": {
    required: false,
    files: [
    { file: "ppge_atlas.zim", md5: "866855cc330b9b95cc69135fb7b41d38", sha1: "30a33f3651f8e1b0967a5dfe6ff714baebcce41a", size: 666530, region: "World", description: "" },
    ],
  },
  "psx": {
    required: true,
    files: [
    { file: "ps1_rom.bin", md5: "81bbe60ba7a3d1cea1d48c14cbcc647b", sha1: "c40146361eb8cf670b19fdc9759190257803cab7", size: 524288, region: "World", description: "" },
    { file: "psxonpsp660.bin", md5: "c53ca5908936d412331790f4426c6c33", sha1: "96880d1ca92a016ff054be5159bb06fe03cb4e14", size: 524288, region: "World", description: "" },
    { file: "scph100.bin", md5: "8abc1b549a4a80954addc48ef02c4521", sha1: "339a48f4fcf63e10b5b867b8c93cfd40945faf6c", size: 524288, region: "World", description: "" },
    { file: "scph1000.bin", md5: "239665b1a3dade1b5a52c06338011044", sha1: "343883a7b555646da8cee54aadd2795b6e7dd070", size: 524288, region: "Japan", description: "" },
    { file: "scph1001.bin", md5: "924e392ed05558ffdb115408c263dccf", sha1: "10155d8d6e6e832d6ea66db9bc098321fb5e8ebf", size: 524288, region: "USA", description: "" },
    { file: "scph1002.bin", md5: "54847e693405ffeb0359c6287434cbef", sha1: "20b98f3d80f11cbf5a7bfd0779b0e63760ecc62c", size: 524288, region: "Europe", description: "" },
    { file: "scph101.bin", md5: "6e3735ff4c7dc899ee98981385f6f3d0", sha1: "dcffe16bd90a723499ad46c641424981338d8378", size: 524288, region: "USA", description: "" },
    { file: "scph102A.bin", md5: "b10f5e0e3d9eb60e5159690680b1e774", sha1: "beb0ac693c0dc26daf5665b3314db81480fa5c7c", size: 524288, region: "World", description: "" },
    { file: "scph102B.bin", md5: "de93caec13d1a141a40a79f5c86168d6", sha1: "dbc7339e5d85827c095764fc077b41f78fd2ecae", size: 524288, region: "World", description: "" },
    { file: "scph102C.bin", md5: "de93caec13d1a141a40a79f5c86168d6", sha1: "dbc7339e5d85827c095764fc077b41f78fd2ecae", size: 524288, region: "World", description: "" },
    { file: "scph3000.bin", md5: "849515939161e62f6b866f6853006780", sha1: "b06f4a861f74270be819aa2a07db8d0563a7cc4e", size: 524288, region: "Japan", description: "" },
    { file: "scph3500.bin", md5: "cba733ceeff5aef5c32254f1d617fa62", sha1: "e38466a4ba8005fba7e9e3c7b9efeba7205bee3f", size: 524288, region: "Japan", description: "" },
    { file: "scph5000.bin", md5: "eb201d2d98251a598af467d4347bb62f", sha1: "e340db2696274dda5fdc25e434a914db71e8b02b", size: 524288, region: "Japan", description: "" },
    { file: "scph5500.bin", md5: "8dd7d5296a650fac7319bce665a6a53c", sha1: "b05def971d8ec59f346f2d9ac21fb742e3eb6917", size: 524288, region: "Japan", description: "" },
    { file: "scph5501.bin", md5: "490f666e1afb15b7362b406ed1cea246", sha1: "0555c6fae8906f3f09baf5988f00e55f88e9f30b", size: 524288, region: "USA", description: "" },
    { file: "scph5502.bin", md5: "32736f17079d0b2b7024407c39bd3050", sha1: "f6bc2d1f5eb6593de7d089c425ac681d6fffd3f0", size: 524288, region: "Europe", description: "" },
    { file: "scph5552.bin", md5: "32736f17079d0b2b7024407c39bd3050", sha1: "f6bc2d1f5eb6593de7d089c425ac681d6fffd3f0", size: 524288, region: "World", description: "" },
    { file: "scph7001.bin", md5: "1e68c231d0896b7eadcad1d7d8e76129", sha1: "14df4f6c1e367ce097c11deae21566b4fe5647a9", size: 524288, region: "USA", description: "" },
    { file: "scph7002.bin", md5: "b9d9a0286c33dc6b7237bb13cd46fdee", sha1: "8d5de56a79954f29e9006929ba3fed9b6a418c1d", size: 524288, region: "Europe", description: "" },
    { file: "scph7003.bin", md5: "490f666e1afb15b7362b406ed1cea246", sha1: "0555c6fae8906f3f09baf5988f00e55f88e9f30b", size: 524288, region: "USA", description: "" },
    { file: "scph7502.bin", md5: "b9d9a0286c33dc6b7237bb13cd46fdee", sha1: "8d5de56a79954f29e9006929ba3fed9b6a418c1d", size: 524288, region: "Europe", description: "" },
    { file: "scph9002(7502).bin", md5: "b9d9a0286c33dc6b7237bb13cd46fdee", sha1: "8d5de56a79954f29e9006929ba3fed9b6a418c1d", size: 524288, region: "World", description: "" },
    ],
  },
  "satellaview": {
    required: false,
    files: [
    { file: "BS-X (En) (DRM-Free).bin", md5: "4ed9648505ab33a4daec93707b16caba", sha1: "7996bd1c01b99800e0d5d34beff93db283784864", size: 1048576, region: "World", description: "" },
    { file: "BS-X (En).bin", md5: "33b62505da6ca4525e3839db4e1a7bca", sha1: "f3cdff70de5d0f5c52ca3a8f46588b863d48b8ec", size: 1048576, region: "World", description: "" },
    { file: "BS-X.bin", md5: "fed4d8242cfbed61343d53d48432aced", sha1: "604556b2e62860af18db5a77f2956ebc75450020", size: 1048576, region: "World", description: "" },
    ],
  },
  "saturn": {
    required: true,
    files: [
    { file: "hisaturn.bin", md5: "3ea3202e2634cb47cb90f3a05c015010", sha1: "49d8493008fa715ca0c94d99817a5439d6f2c796", size: 524288, region: "World", description: "" },
    { file: "kronos/stvbios.zip", md5: "", sha1: "", size: 0, region: "World", description: "" },
    { file: "mpr-17933.bin", md5: "3240872c70984b6cbfda1586cab68dbe", sha1: "faa8ea183a6d7bbe5d4e03bb1332519800d3fbc3", size: 524288, region: "USA", description: "" },
    { file: "mpr-18100.bin", md5: "cb2cebc1b6e573b7c44523d037edcd45", sha1: "8a22710e09ce75f39625894366cafe503ed1942d", size: 524288, region: "World", description: "" },
    { file: "mpr-18811-mx.ic1", md5: "255113ba943c92a54facd25a10fd780c", sha1: "a67cd4f550751f8b91de2b8b74528ab4e0c11c77", size: 2097152, region: "Japan", description: "" },
    { file: "mpr-19367-mx.ic1", md5: "1cd19988d1d72a3e7caa0b73234c96b4", sha1: "56c1b93da6b660bf393fbf48ca47569000ef4047", size: 2097152, region: "Japan", description: "" },
    { file: "saturn_bios.bin", md5: "af5828fdff51384f99b3c4926be27762", sha1: "2b8cb4f87580683eb4d760e4ed210813d667f0a2", size: 524288, region: "World", description: "" },
    { file: "sega_100.bin", md5: "af5828fdff51384f99b3c4926be27762", sha1: "2b8cb4f87580683eb4d760e4ed210813d667f0a2", size: 524288, region: "World", description: "" },
    { file: "sega_100a.bin", md5: "f273555d7d91e8a5a6bfd9bcf066331c", sha1: "3bb41feb82838ab9a35601ac666de5aacfd17a58", size: 524288, region: "World", description: "" },
    { file: "sega_101.bin", md5: "85ec9ca47d8f6807718151cbcca8b964", sha1: "df94c5b4d47eb3cc404d88b33a8fda237eaf4720", size: 524288, region: "Japan", description: "" },
    { file: "sega1003.bin", md5: "74570fed4d44b2682b560c8cd44b8b6a", sha1: "7b23b53d62de0f29a23e423d0fe751dfb469c2fa", size: 524288, region: "World", description: "" },
    { file: "vsaturn.bin", md5: "ac4e4b6522e200c0d23d371a8cecbfd3", sha1: "4154e11959f3d5639b11d7902b3a393a99fb5776", size: 524288, region: "World", description: "" },
    ],
  },
  "segacd": {
    required: true,
    files: [
    { file: "bios_CD_E.bin", md5: "e66fa1dc5820d254611fdcdba0662372", sha1: "f891e0ea651e2232af0c5c4cb46a0cae2ee8f356", size: 131072, region: "Europe", description: "" },
    { file: "bios_CD_J.bin", md5: "278a9397d192149e84e820ac621a8edd", sha1: "4846f448160059a7da0215a5df12ca160f26dd69", size: 131072, region: "Japan", description: "" },
    { file: "bios_CD_U.bin", md5: "2efd74e3232ff260e371b99f84024f7f", sha1: "f4f315adcef9b8feb0364c21ab7f0eaf5457f3ed", size: 131072, region: "USA", description: "" },
    ],
  },
  "sms": {
    required: false,
    files: [
    { file: "bios_E.sms", md5: "840481177270d5642a14ca71ee72844c", sha1: "c315672807d8ddb8d91443729405c766dd95cae7", size: 8192, region: "World", description: "" },
    { file: "bios_J.sms", md5: "24a519c53f67b00640d0048ef7089105", sha1: "a8c1b39a2e41137835eda6a5de6d46dd9fadbaf2", size: 8192, region: "World", description: "" },
    { file: "bios_U.sms", md5: "840481177270d5642a14ca71ee72844c", sha1: "c315672807d8ddb8d91443729405c766dd95cae7", size: 8192, region: "World", description: "" },
    { file: "bios.sms", md5: "840481177270d5642a14ca71ee72844c", sha1: "c315672807d8ddb8d91443729405c766dd95cae7", size: 8192, region: "World", description: "" },
    ],
  },
  "sufami": {
    required: false,
    files: [
    { file: "STBIOS.bin", md5: "d3a44ba7d42a74d3ac58cb9c14c6a5ca", sha1: "ef86ea192eed03d5c413fdbbfd46043be1d7a127", size: 262144, region: "World", description: "" },
    ],
  },
  "zxspectrum": {
    required: false,
    files: [
    { file: "128-0.rom", md5: "b4d2692115a9f2924df92a3cbfb358fb", sha1: "4f4b11ec22326280bdb96e3baf9db4b4cb1d02c5", size: 16384, region: "World", description: "" },
    { file: "128-1.rom", md5: "6e09e5d3c4aef166601669feaaadc01c", sha1: "80080644289ed93d71a1103992a154cc9802b2fa", size: 16384, region: "World", description: "" },
    { file: "128-spanish-0.rom", md5: "c1231a70b8129311216acb7479b031d5", sha1: "968937b1c750f0ef6205f01c6db4148da4cca4e3", size: 16384, region: "World", description: "" },
    { file: "128-spanish-1.rom", md5: "4f341936594cbcab75cfa62ce96e3682", sha1: "bea3f397cc705eafee995ea629f4a82550562f90", size: 16384, region: "World", description: "" },
    { file: "128p-0.rom", md5: "a249565f03b98d004ee7f019570069cd", sha1: "d07fcdeca892ee80494d286ea9ea5bf3928a1aca", size: 16384, region: "World", description: "" },
    { file: "128p-1.rom", md5: "6e09e5d3c4aef166601669feaaadc01c", sha1: "80080644289ed93d71a1103992a154cc9802b2fa", size: 16384, region: "World", description: "" },
    { file: "256s-0.rom", md5: "b9fda5b6a747ff037365b0e2d8c4379a", sha1: "477114ff0fe1388e0979df1423602b21248164e5", size: 16384, region: "World", description: "" },
    { file: "256s-1.rom", md5: "643861ad34831b255bf2eb64e8b6ecb8", sha1: "367b5a102fb663beee8e7930b8c4acc219c1f7b3", size: 16384, region: "World", description: "" },
    { file: "256s-2.rom", md5: "d8ad507b1c915a9acfe0d73957082926", sha1: "07783ee295274d8ff15d935bfd787c8ac1d54900", size: 16384, region: "World", description: "" },
    { file: "256s-3.rom", md5: "ce0723f9bc02f4948c15d3b3230ae831", sha1: "33703e97cc93b7edfcc0334b64233cf81b7930db", size: 16384, region: "World", description: "" },
    { file: "48.rom", md5: "4c42a2f075212361c3117015b107ff68", sha1: "5ea7c2b824672e914525d1d5c419d71b84a426a2", size: 16384, region: "World", description: "" },
    { file: "disciple.rom", md5: "78e61a2a02121873c1756b21fd1398b1", sha1: "9a75ed4b293f968985be4c9aa893cd88276d1ced", size: 8192, region: "World", description: "" },
    { file: "disk_plus3.szx", md5: "e6db6b9f6ad15012851115a7bc4b31d8", sha1: "d7896640e18fc6204aa494835b0a430250fb06ce", size: 1568, region: "World", description: "" },
    { file: "gluck.rom", md5: "d5869034604dbfd2c1d54170e874fd0a", sha1: "015eb96dafb273d4f4512c467e9b43c305fd1bc4", size: 16384, region: "World", description: "" },
    { file: "if1-1.rom", md5: "5c11c61a2dd2ca4bf39328d9ff42d289", sha1: "4ffd9ed9c00cdc6f92ce69fdd8b618ef1203f48e", size: 8192, region: "World", description: "" },
    { file: "if1-2.rom", md5: "31b704ae925305e74f50699271fddd9a", sha1: "5cfb6bca4177c45fefd571734576b55e3a127c08", size: 8192, region: "World", description: "" },
    { file: "plus2-0.rom", md5: "4ed7af4636308b8a48d7a35e6c5b546b", sha1: "72703f9a3e734f3c23ec34c0727aae4ccbef9a91", size: 16384, region: "World", description: "" },
    { file: "plus2-1.rom", md5: "b3db95931cc844efaeb82db9c171b9f3", sha1: "de8b0d2d0379cfe7c39322a086ca6da68c7f23cb", size: 16384, region: "World", description: "" },
    { file: "plus3-0.rom", md5: "9833b8b73384dd5fa3678377ff00a2bb", sha1: "e319ed08b4d53a5e421a75ea00ea02039ba6555b", size: 16384, region: "World", description: "" },
    { file: "plus3-1.rom", md5: "0f711ceb5ab801b4701989982e0f334c", sha1: "c9969fc36095a59787554026a9adc3b87678c794", size: 16384, region: "World", description: "" },
    { file: "plus3-2.rom", md5: "3b6dd659d5e4ec97f0e2f7878152c987", sha1: "22e50c6ba4157a3f6a821bd9937cd26e292775c6", size: 16384, region: "World", description: "" },
    { file: "plus3-3.rom", md5: "a148bcc575e51389e84fdf5d555c3196", sha1: "65f031caa8148a5493afe42c41f4929deab26b4e", size: 16384, region: "World", description: "" },
    { file: "plus3e-0.rom", md5: "bc123f625e245c225f92ef05933ed134", sha1: "649fbd233490bf58b35350b0123d36caaaa011eb", size: 16384, region: "World", description: "" },
    { file: "plus3e-1.rom", md5: "617364264c587d20c9fc4746c29679f2", sha1: "f12198108cbb14de4f03c6695bc16d08c85ee214", size: 16384, region: "World", description: "" },
    { file: "plus3e-2.rom", md5: "c363e95dcd0a90e6e7f847e6e47e0179", sha1: "773633dce5ba323a9e00d9d0f9e4d8c295df7c87", size: 16384, region: "World", description: "" },
    { file: "plus3e-3.rom", md5: "a148bcc575e51389e84fdf5d555c3196", sha1: "65f031caa8148a5493afe42c41f4929deab26b4e", size: 16384, region: "World", description: "" },
    { file: "plusd.rom", md5: "42e5de16fb5e50082bb954ec7ce45851", sha1: "6b841dc5797ef7eb219ad455cd1e434ca3b9d30d", size: 8192, region: "World", description: "" },
    { file: "se-0.rom", md5: "fb3f86eb1e5a695d9c50c124e7cfb875", sha1: "8608328d7dd66602a4846f046b24fed500f7d828", size: 16384, region: "World", description: "" },
    { file: "se-1.rom", md5: "88de4a3129086f34bb9ca559acc51e6c", sha1: "3be5de57dd3bd0a9d15c57cabe9179afe2906a52", size: 16384, region: "World", description: "" },
    { file: "speccyboot-1.4.rom", md5: "c54aa8f374b0971f51546c29d5d1eba1", sha1: "16af6f052b38a027dd49ba6e96e3a59d16b62672", size: 8192, region: "World", description: "" },
    { file: "tape_128.szx", md5: "8942b43b73ed4eb7f32bd1741709a4dc", sha1: "3b1287bfc6fec9c7dd838f6ea1706698cb96fd16", size: 1464, region: "World", description: "" },
    { file: "tape_16.szx", md5: "fec97eb9ea1b017cae84de78508feb4a", sha1: "ec9e5607ce7faf2d6a5d71e5e21188ca86e963a1", size: 591, region: "World", description: "" },
    { file: "tape_2048.szx", md5: "116f732bbae4e49d625aaf2f311474d0", sha1: "f2d2227dce697df8aac78883eaf966e71435caa3", size: 720, region: "World", description: "" },
    { file: "tape_2068.szx", md5: "0b0f267b95d556318bb652af2e8dc25c", sha1: "5af71025c02358b325bf8b4bfaa2662488abf1d2", size: 1799, region: "World", description: "" },
    { file: "tape_48.szx", md5: "ee2ae810711594db3a134a7432baabff", sha1: "d6e092730f822c9e8828ca12f54eb8d65228f30c", size: 708, region: "World", description: "" },
    { file: "tape_pentagon.szx", md5: "bd7698603bd9079d337cdedfb04942d9", sha1: "7e1eb0e250cfe1f2f0e50f734378a738e8bf327f", size: 1479, region: "World", description: "" },
    { file: "tape_plus2.szx", md5: "166d4aa1a5aa4fbd99cc963b4e7c19cc", sha1: "4a6d8941eee86d7e52452f5aaaa73d4bafe9bde1", size: 1571, region: "World", description: "" },
    { file: "tape_plus2a.szx", md5: "445d4817d5557bb363a216fbd6eeaa84", sha1: "e0e0f6ebc8261ae9768a6be772eab4718fbc2395", size: 1617, region: "World", description: "" },
    { file: "tape_plus3.szx", md5: "0dc8828ac1db2e0efa915ac55191e96f", sha1: "3850f7e5e6c90fd4dac988da77717d2647d9c021", size: 1856, region: "World", description: "" },
    { file: "tape_plus3e.szx", md5: "bf07537f028bbcb3309464bd30da779c", sha1: "92ac0df41f3ea7f147f4d6bae6b8a7d79b4f7e92", size: 1970, region: "World", description: "" },
    { file: "tape_scorpion.szx", md5: "c10e677d3deb5a445689d3a599880745", sha1: "6abdeb434755d25a280954ce07b50b6a28b36957", size: 3500, region: "World", description: "" },
    { file: "tape_se.szx", md5: "2518f9334bef8c44804a4185085579b5", sha1: "cc20a8e6fc8c493881b14e00545a42ef75b8aabe", size: 2146, region: "World", description: "" },
    { file: "tape_ts2068.szx", md5: "1d360c09d370bb52a9a44b30cc7c59e6", sha1: "562298f5b3a7ed28f0129b066e8ad098a10e2270", size: 1840, region: "World", description: "" },
    { file: "tc2048.rom", md5: "9dd7ecf784a6c04265c073c236f5fadb", sha1: "febb2d495b6eda7cdcb4074935d6e9d9f328972d", size: 16384, region: "World", description: "" },
    { file: "tc2068-0.rom", md5: "55d462fccc6c536037404ef4ced08bec", sha1: "1446cb2780a9dedf640404a639fa3ae518b2d8aa", size: 16384, region: "World", description: "" },
    { file: "tc2068-1.rom", md5: "575d203c6e15e679fba0b73f854ec7a2", sha1: "7e265a2c1f621ed365ea23bdcafdedbc79c1299c", size: 8192, region: "World", description: "" },
    { file: "trdos.rom", md5: "0da70a5d2a0e733398e005b96b7e4ba6", sha1: "21695e3f2a8f796386ce66eea8a246b0ac44810c", size: 16384, region: "World", description: "" },
    { file: "zx128.rom", md5: "85fede415f4294cc777517d7eada482e", sha1: "16375d42ea109b47edded7a16028de7fdb3013a1", size: 32768, region: "World", description: "" },
    { file: "zx48.rom", md5: "4c42a2f075212361c3117015b107ff68", sha1: "5ea7c2b824672e914525d1d5c419d71b84a426a2", size: 16384, region: "World", description: "" },
    ],
  },
};

/** All hashes → the system+file they identify, for matching uploads by content. */
export interface BiosMatch { slug: string; file: BiosFile; }
const BY_HASH: Record<string, BiosMatch> = (() => {
  const m: Record<string, BiosMatch> = {};
  for (const [slug, sys] of Object.entries(BIOS_MANIFEST)) {
    for (const file of sys.files) {
      if (file.sha1) m["sha1:" + file.sha1] = { slug, file };
      if (file.md5) m["md5:" + file.md5] = { slug, file };
    }
  }
  return m;
})();

/** Identify an uploaded file by content hash (sha1 preferred, md5 fallback). */
export function matchBiosByHash(hashes: { sha1?: string; md5?: string }): BiosMatch | null {
  if (hashes.sha1 && BY_HASH["sha1:" + hashes.sha1.toLowerCase()]) return BY_HASH["sha1:" + hashes.sha1.toLowerCase()];
  if (hashes.md5 && BY_HASH["md5:" + hashes.md5.toLowerCase()]) return BY_HASH["md5:" + hashes.md5.toLowerCase()];
  return null;
}
