// Platform registry: maps file extensions and folder names to platforms,
// emulator (libretro) cores, and libretro-thumbnails system names.

export interface Platform {
  slug: string;
  name: string;
  shortName: string;
  /** File extensions (lowercase, with dot) that uniquely identify this platform */
  extensions: string[];
  /** Folder-name aliases (lowercase) used to resolve ambiguous extensions like .zip/.bin/.iso */
  folderAliases: string[];
  /** EmulatorJS core id used to play this system in-browser; null = not
   *  emulated (e.g. Flash, which plays via Ruffle) */
  ejsCore: string | null;
  /** System directory name on thumbnails.libretro.com */
  libretroName: string;
  /** Accent color used for platform badges / placeholder art */
  color: string;
  /**
   * Folder-based games (e.g. an extracted Wii U title). A directory that
   * contains ALL of these child entries is treated as a single ROM — the
   * scanner records the folder itself and does not descend into it.
   */
  folderRom?: { requires: string[] };
}

export const PLATFORMS: Platform[] = [
  {
    slug: "nes",
    name: "Nintendo Entertainment System",
    shortName: "NES",
    extensions: [".nes", ".unf"],
    folderAliases: ["nes", "nintendo nes", "nintendo entertainment system"],
    ejsCore: "nes",
    libretroName: "Nintendo - Nintendo Entertainment System",
    color: "#e60012",
  },
  {
    slug: "snes",
    name: "Super Nintendo",
    shortName: "SNES",
    extensions: [".sfc", ".smc"],
    folderAliases: [
      "snes",
      "super nintendo",
      "super nes",
      "super nintendo entertainment system",
      "nintendo super nintendo",
      "nintendo snes",
    ],
    ejsCore: "snes",
    libretroName: "Nintendo - Super Nintendo Entertainment System",
    color: "#7c6bc4",
  },
  {
    slug: "n64",
    name: "Nintendo 64",
    shortName: "N64",
    extensions: [".n64", ".z64", ".v64"],
    folderAliases: ["n64", "nintendo 64", "nintendo64"],
    ejsCore: "n64",
    libretroName: "Nintendo - Nintendo 64",
    color: "#009e60",
  },
  {
    slug: "gb",
    name: "Game Boy",
    shortName: "GB",
    extensions: [".gb"],
    folderAliases: ["gb", "gameboy", "game boy"],
    ejsCore: "gb",
    libretroName: "Nintendo - Game Boy",
    color: "#8b956d",
  },
  {
    slug: "gbc",
    name: "Game Boy Color",
    shortName: "GBC",
    extensions: [".gbc"],
    folderAliases: ["gbc", "gameboy color", "game boy color"],
    ejsCore: "gb",
    libretroName: "Nintendo - Game Boy Color",
    color: "#a839c4",
  },
  {
    slug: "gba",
    name: "Game Boy Advance",
    shortName: "GBA",
    extensions: [".gba"],
    folderAliases: ["gba", "gameboy advance", "game boy advance", "game boy adavnce"],
    ejsCore: "gba",
    libretroName: "Nintendo - Game Boy Advance",
    color: "#5c67c9",
  },
  {
    slug: "nds",
    name: "Nintendo DS",
    shortName: "NDS",
    extensions: [".nds"],
    folderAliases: ["nds", "ds", "nintendo ds", "dsi", "nintendo dsi"],
    ejsCore: "nds",
    libretroName: "Nintendo - Nintendo DS",
    color: "#b0b0b0",
  },
  {
    slug: "genesis",
    name: "Sega Genesis",
    shortName: "Genesis",
    extensions: [".gen", ".smd"],
    folderAliases: ["genesis", "sega genesis"],
    ejsCore: "segaMD",
    libretroName: "Sega - Mega Drive - Genesis",
    color: "#1665c0",
  },
  {
    slug: "sms",
    name: "Sega Master System",
    shortName: "SMS",
    extensions: [".sms"],
    folderAliases: ["sms", "master system", "sega master system", "samsung gameboy", "samsung gam boy"],
    ejsCore: "segaMS",
    libretroName: "Sega - Master System - Mark III",
    color: "#d32f2f",
  },
  {
    slug: "gg",
    name: "Sega Game Gear",
    shortName: "GG",
    extensions: [".gg"],
    folderAliases: ["gg", "game gear", "gamegear"],
    ejsCore: "segaGG",
    libretroName: "Sega - Game Gear",
    color: "#455a64",
  },
  {
    slug: "psx",
    name: "PlayStation",
    shortName: "PS1",
    extensions: [".pbp"],
    folderAliases: ["psx", "ps1", "ps", "playstation", "sony playstation"],
    ejsCore: "psx",
    libretroName: "Sony - PlayStation",
    color: "#9aa0a6",
  },
  {
    slug: "atari2600",
    name: "Atari 2600",
    shortName: "2600",
    extensions: [".a26"],
    folderAliases: ["atari", "atari 2600", "atari2600", "2600"],
    ejsCore: "atari2600",
    libretroName: "Atari - 2600",
    color: "#c1440e",
  },
  {
    slug: "pce",
    name: "TurboGrafx-16",
    shortName: "TG-16",
    extensions: [],
    folderAliases: ["turbografx", "turbografx-16", "turbografx 16", "tg16"],
    ejsCore: "pce",
    libretroName: "NEC - PC Engine - TurboGrafx 16",
    color: "#ef6c00",
  },
  {
    slug: "vb",
    name: "Virtual Boy",
    shortName: "VB",
    extensions: [".vb", ".vboy"],
    folderAliases: ["vb", "virtual boy", "virtualboy"],
    ejsCore: "vb",
    libretroName: "Nintendo - Virtual Boy",
    color: "#c62828",
  },
  {
    slug: "3ds",
    name: "Nintendo 3DS",
    shortName: "3DS",
    extensions: [".3ds", ".cia"],
    folderAliases: ["3ds", "nintendo 3ds", "n3ds"],
    ejsCore: null,
    libretroName: "Nintendo - Nintendo 3DS",
    color: "#d32f2f",
  },
  {
    slug: "gamecube",
    name: "Nintendo GameCube",
    shortName: "GC",
    extensions: [".gcm", ".rvz", ".gcz"],
    folderAliases: ["gamecube", "gc", "ngc", "nintendo gamecube"],
    ejsCore: null,
    libretroName: "Nintendo - GameCube",
    color: "#5c6bc0",
  },
  {
    slug: "wii",
    name: "Nintendo Wii",
    shortName: "Wii",
    extensions: [".wbfs"],
    folderAliases: ["wii", "nintendo wii"],
    ejsCore: null,
    libretroName: "Nintendo - Wii",
    color: "#8d99ae",
  },
  {
    slug: "wiiu",
    name: "Nintendo Wii U",
    shortName: "Wii U",
    extensions: [".wua", ".wux", ".wud"],
    folderAliases: ["wiiu", "wii u", "nintendo wii u"],
    ejsCore: null,
    libretroName: "Nintendo - Wii U",
    color: "#26a9e0",
    // Extracted Wii U titles are a folder with code/ content/ meta/ inside.
    folderRom: { requires: ["code", "content", "meta"] },
  },
  {
    slug: "switch",
    name: "Nintendo Switch",
    shortName: "Switch",
    extensions: [".nsp", ".xci"],
    folderAliases: ["switch", "nintendo switch", "nsw"],
    ejsCore: null,
    libretroName: "Nintendo - Nintendo Switch",
    color: "#e60012",
  },
  {
    slug: "segacd",
    name: "Sega CD",
    shortName: "Sega CD",
    extensions: [],
    folderAliases: ["sega cd", "segacd"],
    ejsCore: "segaCD",
    libretroName: "Sega - Mega-CD - Sega CD",
    color: "#283593",
  },
  {
    slug: "sega32x",
    name: "Sega 32X",
    shortName: "32X",
    extensions: [".32x"],
    folderAliases: ["32x", "sega 32x"],
    ejsCore: "sega32x",
    libretroName: "Sega - 32X",
    color: "#6d4c41",
  },
  {
    slug: "saturn",
    name: "Sega Saturn",
    shortName: "Saturn",
    extensions: [],
    folderAliases: ["saturn", "sega saturn"],
    ejsCore: "segaSaturn",
    libretroName: "Sega - Saturn",
    color: "#455a64",
  },
  {
    slug: "dreamcast",
    name: "Sega Dreamcast",
    shortName: "DC",
    extensions: [".gdi", ".cdi"],
    folderAliases: ["dreamcast", "dc", "sega dreamcast"],
    ejsCore: null,
    libretroName: "Sega - Dreamcast",
    color: "#f57f17",
  },
  {
    slug: "ps2",
    name: "PlayStation 2",
    shortName: "PS2",
    extensions: [],
    folderAliases: ["ps2", "playstation 2", "sony playstation 2"],
    ejsCore: null,
    libretroName: "Sony - PlayStation 2",
    color: "#1a237e",
  },
  {
    slug: "psp",
    name: "PlayStation Portable",
    shortName: "PSP",
    extensions: [".cso"],
    folderAliases: ["psp", "playstation portable", "sony psp", "sony playstation portable"],
    ejsCore: "psp",
    libretroName: "Sony - PlayStation Portable",
    color: "#37474f",
  },
  {
    slug: "vita",
    name: "PlayStation Vita",
    shortName: "Vita",
    extensions: [".vpk"],
    folderAliases: ["vita", "ps vita", "psvita", "playstation vita"],
    ejsCore: null,
    libretroName: "Sony - PlayStation Vita",
    color: "#0d47a1",
  },
  {
    slug: "atari5200",
    name: "Atari 5200",
    shortName: "5200",
    extensions: [".a52"],
    folderAliases: ["atari 5200", "atari5200", "5200"],
    ejsCore: "atari5200",
    libretroName: "Atari - 5200",
    color: "#8d6e63",
  },
  {
    slug: "atari7800",
    name: "Atari 7800",
    shortName: "7800",
    extensions: [".a78"],
    folderAliases: ["atari 7800", "atari7800", "7800"],
    ejsCore: "atari7800",
    libretroName: "Atari - 7800",
    color: "#795548",
  },
  {
    slug: "lynx",
    name: "Atari Lynx",
    shortName: "Lynx",
    extensions: [".lnx"],
    folderAliases: ["lynx", "atari lynx"],
    ejsCore: "lynx",
    libretroName: "Atari - Lynx",
    color: "#ff8f00",
  },
  {
    slug: "jaguar",
    name: "Atari Jaguar",
    shortName: "Jaguar",
    extensions: [".j64", ".jag"],
    folderAliases: ["jaguar", "atari jaguar"],
    ejsCore: "jaguar",
    libretroName: "Atari - Jaguar",
    color: "#b71c1c",
  },
  {
    slug: "ngp",
    name: "Neo Geo Pocket / Color",
    shortName: "NGP",
    extensions: [".ngp", ".ngc"],
    folderAliases: ["ngp", "ngpc", "neo geo pocket", "neo geo pocket color"],
    ejsCore: "ngp",
    libretroName: "SNK - Neo Geo Pocket Color",
    color: "#00695c",
  },
  {
    slug: "wonderswan",
    name: "WonderSwan / Color",
    shortName: "WS",
    extensions: [".ws", ".wsc"],
    folderAliases: ["wonderswan", "wonderswan color", "ws", "wsc"],
    ejsCore: "ws",
    libretroName: "Bandai - WonderSwan Color",
    color: "#4527a0",
  },
  {
    slug: "coleco",
    name: "ColecoVision",
    shortName: "Coleco",
    extensions: [".col"],
    folderAliases: ["coleco", "colecovision"],
    ejsCore: "coleco",
    libretroName: "Coleco - ColecoVision",
    color: "#4e342e",
  },
  {
    slug: "intellivision",
    name: "Intellivision",
    shortName: "INTV",
    extensions: [".int"],
    folderAliases: ["intellivision", "intv", "mattel intellivision"],
    ejsCore: null,
    libretroName: "Mattel - Intellivision",
    color: "#5d4037",
  },
  {
    slug: "pcfx",
    name: "PC-FX",
    shortName: "PC-FX",
    extensions: [],
    folderAliases: ["pcfx", "pc-fx", "nec pc-fx"],
    ejsCore: "pcfx",
    libretroName: "NEC - PC-FX",
    color: "#c2185b",
  },
  {
    slug: "pcecd",
    name: "TurboGrafx-CD",
    shortName: "TG-CD",
    extensions: [],
    folderAliases: ["pcecd", "turbografx cd", "turbografx-cd"],
    ejsCore: "pce",
    libretroName: "NEC - PC Engine CD - TurboGrafx-CD",
    color: "#e65100",
  },
  {
    slug: "arcade",
    name: "Arcade (MAME / FBNeo)",
    shortName: "Arcade",
    extensions: [],
    folderAliases: ["arcade", "mame", "fbneo", "fba", "final burn alpha", "fbalpha"],
    ejsCore: "arcade",
    libretroName: "FBNeo - Arcade Games",
    color: "#9c27b0",
  },
  {
    slug: "neogeo",
    name: "Neo Geo",
    shortName: "Neo Geo",
    extensions: [],
    folderAliases: ["neogeo", "neo geo", "neo-geo", "snk neo geo"],
    ejsCore: "arcade",
    libretroName: "FBNeo - Arcade Games",
    color: "#01579b",
  },
  {
    slug: "3do",
    name: "3DO",
    shortName: "3DO",
    extensions: [],
    folderAliases: ["3do", "panasonic 3do"],
    ejsCore: "3do",
    libretroName: "The 3DO Company - 3DO",
    color: "#33691e",
  },
  {
    slug: "msx",
    name: "MSX",
    shortName: "MSX",
    extensions: [".mx1", ".mx2"],
    folderAliases: ["msx", "msx2", "microsoft msx"],
    ejsCore: null,
    libretroName: "Microsoft - MSX",
    color: "#00838f",
  },
  {
    slug: "c64",
    name: "Commodore 64",
    shortName: "C64",
    extensions: [".d64", ".t64", ".prg"],
    folderAliases: ["c64", "commodore 64", "commodore64"],
    ejsCore: null,
    libretroName: "Commodore - 64",
    color: "#3e2723",
  },
  {
    slug: "amiga",
    name: "Commodore Amiga",
    shortName: "Amiga",
    extensions: [".adf", ".lha"],
    folderAliases: ["amiga", "commodore amiga"],
    ejsCore: null,
    libretroName: "Commodore - Amiga",
    color: "#bf360c",
  },
  {
    slug: "dos",
    name: "DOS",
    shortName: "DOS",
    extensions: [],
    folderAliases: ["dos", "ms-dos", "msdos", "microsoft ms-dos"],
    ejsCore: null,
    libretroName: "DOS",
    color: "#212121",
  },
  {
    slug: "vectrex",
    name: "Vectrex",
    shortName: "Vectrex",
    extensions: [".vec"],
    folderAliases: ["vectrex", "gce vectrex"],
    ejsCore: null,
    libretroName: "GCE - Vectrex",
    color: "#1b5e20",
  },
  {
    slug: "ps3",
    name: "PlayStation 3",
    shortName: "PS3",
    extensions: [],
    folderAliases: ["ps3", "playstation 3", "sony playstation 3"],
    ejsCore: null,
    libretroName: "Sony - PlayStation 3",
    color: "#263238",
  },
  {
    slug: "gandw",
    name: "Game & Watch",
    shortName: "G&W",
    extensions: [".mgw"],
    folderAliases: ["g-and-w", "g and w", "gw", "game & watch", "game and watch", "game watch", "gamewatch"],
    ejsCore: null,
    libretroName: "Handheld Electronic Game",
    color: "#f9a825",
  },
  {
    slug: "atari800",
    name: "Atari 8-bit",
    shortName: "A800",
    extensions: [".atr", ".xex"],
    folderAliases: ["atari8bit", "atari 8-bit", "atari 800", "atari800"],
    ejsCore: null,
    libretroName: "Atari - 8-bit",
    color: "#6d4c41",
  },
  {
    slug: "appleii",
    name: "Apple II",
    shortName: "Apple II",
    extensions: [".dsk", ".po"],
    folderAliases: ["appleii", "apple ii", "apple2"],
    ejsCore: null,
    libretroName: "Apple - II",
    color: "#9e9e9e",
  },
  {
    slug: "acpc",
    name: "Amstrad CPC",
    shortName: "CPC",
    extensions: [".cpr"],
    folderAliases: ["acpc", "amstrad", "amstrad cpc", "cpc"],
    ejsCore: null,
    libretroName: "Amstrad - CPC",
    color: "#00695c",
  },
  {
    slug: "zxspectrum",
    name: "ZX Spectrum",
    shortName: "ZX",
    extensions: [".tzx", ".z80", ".tap"],
    folderAliases: ["zxs", "zx spectrum", "spectrum", "sinclair zx spectrum"],
    ejsCore: null,
    libretroName: "Sinclair - ZX Spectrum",
    color: "#616161",
  },
  {
    slug: "sg1000",
    name: "Sega SG-1000",
    shortName: "SG-1000",
    extensions: [".sg"],
    folderAliases: ["sg-1000", "sg1000", "sega sg-1000", "othello multivision"],
    ejsCore: "segaMS",
    libretroName: "Sega - SG-1000",
    color: "#b0413e",
  },
  {
    slug: "supergrafx",
    name: "NEC SuperGrafx",
    shortName: "SGX",
    extensions: [".sgx"],
    folderAliases: ["supergrafx", "super grafx", "nec supergrafx", "sgx"],
    ejsCore: "pce",
    libretroName: "NEC - PC Engine SuperGrafx",
    color: "#ef6c00",
  },
  {
    slug: "satellaview",
    name: "Nintendo Satellaview (BS-X)",
    shortName: "BS-X",
    extensions: [".bs"],
    folderAliases: ["satellaview", "bs-x", "bsx", "bs-x satellaview"],
    ejsCore: "snes",
    libretroName: "Nintendo - Satellaview",
    color: "#7c6bc4",
  },
  {
    slug: "sufami",
    name: "Nintendo Sufami Turbo",
    shortName: "Sufami",
    extensions: [".st"],
    folderAliases: ["sufami", "sufami turbo"],
    ejsCore: "snes",
    libretroName: "Nintendo - Sufami Turbo",
    color: "#8e6bc4",
  },
  {
    slug: "n64dd",
    name: "Nintendo 64DD",
    shortName: "64DD",
    extensions: [".ndd"],
    folderAliases: ["n64dd", "64dd", "nintendo 64dd"],
    ejsCore: "n64",
    libretroName: "Nintendo - Nintendo 64DD",
    color: "#00796b",
  },
  {
    slug: "pokemini",
    name: "Pokémon Mini",
    shortName: "PokeMini",
    extensions: [".min"],
    folderAliases: ["pokemon mini", "pokemini", "nintendo pokemon mini"],
    ejsCore: null,
    libretroName: "Nintendo - Pokemon Mini",
    color: "#fbc02d",
  },
  {
    slug: "wiiware",
    name: "Nintendo WiiWare",
    shortName: "WiiWare",
    extensions: [".wad"],
    folderAliases: ["wiiware", "nintendo wiiware"],
    ejsCore: null,
    libretroName: "Nintendo - Wii (Digital)",
    color: "#78909c",
  },
  {
    slug: "megaduck",
    name: "Creatronic Mega Duck",
    shortName: "MegaDuck",
    extensions: [],
    folderAliases: ["mega duck", "megaduck", "creatronic mega duck"],
    ejsCore: null,
    libretroName: "Creatronic - Mega Duck",
    color: "#827717",
  },
  {
    slug: "channelf",
    name: "Fairchild Channel F",
    shortName: "Channel F",
    extensions: [".chf"],
    folderAliases: ["channel f", "channelf", "fairchild channel f", "fairchild"],
    ejsCore: null,
    libretroName: "Fairchild - Channel F",
    color: "#4e342e",
  },
  {
    slug: "odyssey2",
    name: "Magnavox Odyssey 2",
    shortName: "Odyssey²",
    extensions: [],
    folderAliases: ["odyssey 2", "odyssey2", "magnavox odyssey 2", "videopac"],
    ejsCore: null,
    libretroName: "Magnavox - Odyssey2",
    color: "#37474f",
  },
  {
    slug: "arcadia2001",
    name: "Emerson Arcadia 2001",
    shortName: "Arcadia",
    extensions: [],
    folderAliases: ["arcadia 2001", "arcadia2001", "emerson arcadia 2001"],
    ejsCore: null,
    libretroName: "Emerson - Arcadia 2001",
    color: "#546e7a",
  },
  {
    slug: "astrocade",
    name: "Bally Astrocade",
    shortName: "Astrocade",
    extensions: [],
    folderAliases: ["astrocade", "bally astrocade", "bally"],
    ejsCore: null,
    libretroName: "Bally - Astrocade",
    color: "#6a1b9a",
  },
  {
    slug: "adventurevision",
    name: "Entex Adventure Vision",
    shortName: "AdvVision",
    extensions: [],
    folderAliases: ["adventure vision", "adventurevision", "entex adventure vision"],
    ejsCore: null,
    libretroName: "Entex - Adventure Vision",
    color: "#c62828",
  },
  {
    slug: "gamepocket",
    name: "Epoch Game Pocket Computer",
    shortName: "GPC",
    extensions: [],
    folderAliases: ["game pocket computer", "epoch game pocket computer"],
    ejsCore: null,
    libretroName: "Epoch - Game Pocket Computer",
    color: "#7b1fa2",
  },
  {
    slug: "scv",
    name: "Epoch Super Cassette Vision",
    shortName: "SCV",
    extensions: [],
    folderAliases: ["super cassette vision", "epoch super cassette vision", "scv"],
    ejsCore: null,
    libretroName: "Epoch - Super Cassette Vision",
    color: "#ad1457",
  },
  {
    slug: "supervision8000",
    name: "Bandai Super Vision 8000",
    shortName: "SV8000",
    extensions: [],
    folderAliases: ["super vision 8000", "supervision 8000", "bandai super vision 8000"],
    ejsCore: null,
    libretroName: "Bandai - Super Vision 8000",
    color: "#00695c",
  },
  {
    slug: "pv1000",
    name: "Casio PV-1000",
    shortName: "PV-1000",
    extensions: [],
    folderAliases: ["pv-1000", "pv1000", "casio pv-1000"],
    ejsCore: null,
    libretroName: "Casio - PV-1000",
    color: "#0277bd",
  },
  {
    slug: "pv2000",
    name: "Casio PV-2000",
    shortName: "PV-2000",
    extensions: [],
    folderAliases: ["pv-2000", "pv2000", "casio pv-2000"],
    ejsCore: null,
    libretroName: "Casio - PV-2000",
    color: "#01579b",
  },
  {
    slug: "vc4000",
    name: "Interton VC 4000",
    shortName: "VC 4000",
    extensions: [],
    folderAliases: ["vc 4000", "vc4000", "interton vc 4000", "interton"],
    ejsCore: null,
    libretroName: "Interton - VC 4000",
    color: "#33691e",
  },
  {
    slug: "vic20",
    name: "Commodore VIC-20",
    shortName: "VIC-20",
    extensions: [".v20"],
    folderAliases: ["vic-20", "vic20", "commodore vic-20", "commodore vic20"],
    ejsCore: null,
    libretroName: "Commodore - VIC-20",
    color: "#4e342e",
  },
  {
    slug: "cdtv",
    name: "Commodore CDTV",
    shortName: "CDTV",
    extensions: [],
    folderAliases: ["cdtv", "commodore cdtv"],
    ejsCore: null,
    libretroName: "Commodore - CDTV",
    color: "#5d4037",
  },
  {
    slug: "maxmachine",
    name: "Commodore MAX Machine",
    shortName: "MAX",
    extensions: [],
    folderAliases: ["max machine", "commodore max machine", "ultimax"],
    ejsCore: null,
    libretroName: "Commodore - MAX Machine",
    color: "#6d4c41",
  },
  {
    slug: "archimedes",
    name: "Acorn Archimedes",
    shortName: "Archie",
    extensions: [],
    folderAliases: ["archimedes", "acorn archimedes"],
    ejsCore: null,
    libretroName: "Acorn - Archimedes",
    color: "#00838f",
  },
  {
    slug: "bbcmicro",
    name: "Acorn BBC Micro",
    shortName: "BBC",
    extensions: [".ssd", ".dsd"],
    folderAliases: ["bbc micro", "bbcmicro", "acorn bbc micro", "bbc"],
    ejsCore: null,
    libretroName: "BBC Microcomputer System",
    color: "#37474f",
  },
  {
    slug: "electron",
    name: "Acorn Electron",
    shortName: "Electron",
    extensions: [],
    folderAliases: ["electron", "acorn electron"],
    ejsCore: null,
    libretroName: "Acorn - Electron",
    color: "#455a64",
  },
  {
    slug: "exidysorcerer",
    name: "Exidy Sorcerer",
    shortName: "Sorcerer",
    extensions: [],
    folderAliases: ["sorcerer", "exidy sorcerer", "exidy"],
    ejsCore: null,
    libretroName: "Exidy - Sorcerer",
    color: "#4527a0",
  },
  {
    slug: "mikrosha",
    name: "Mikrosha",
    shortName: "Mikrosha",
    extensions: [],
    folderAliases: ["mikrosha"],
    ejsCore: null,
    libretroName: "Mikrosha",
    color: "#616161",
  },
  {
    slug: "vg5000",
    name: "Philips VG 5000",
    shortName: "VG5000",
    extensions: [],
    folderAliases: ["vg 5000", "vg5000", "philips vg 5000", "phillips vg 5000"],
    ejsCore: null,
    libretroName: "Philips - VG 5000",
    color: "#1565c0",
  },
  {
    slug: "cdi",
    name: "Philips CD-i",
    shortName: "CD-i",
    extensions: [],
    folderAliases: ["cd-i", "cdi", "philips cd-i", "phillips cd-i"],
    ejsCore: null,
    libretroName: "Philips - CD-i",
    color: "#0d47a1",
  },
  {
    slug: "xbox",
    name: "Microsoft Xbox",
    shortName: "Xbox",
    extensions: [],
    folderAliases: ["xbox", "microsoft xbox"],
    ejsCore: null,
    libretroName: "Microsoft - Xbox",
    color: "#2e7d32",
  },
  {
    slug: "xbox360",
    name: "Microsoft Xbox 360",
    shortName: "X360",
    extensions: [],
    folderAliases: ["xbox 360", "xbox360", "x360", "microsoft xbox 360"],
    ejsCore: null,
    libretroName: "Microsoft - Xbox 360",
    color: "#43a047",
  },
  {
    slug: "ouya",
    name: "Ouya",
    shortName: "Ouya",
    extensions: [],
    folderAliases: ["ouya"],
    ejsCore: null,
    libretroName: "Ouya",
    color: "#757575",
  },
  {
    slug: "segapico",
    name: "Sega Pico",
    shortName: "Pico",
    extensions: [],
    folderAliases: ["pico", "sega pico"],
    ejsCore: null,
    libretroName: "Sega - PICO",
    color: "#e53935",
  },
  {
    slug: "naomi",
    name: "Sega Naomi",
    shortName: "Naomi",
    extensions: [],
    folderAliases: ["naomi", "sega naomi"],
    ejsCore: null,
    libretroName: "Sega - Naomi",
    color: "#8e24aa",
  },
  {
    slug: "naomi2",
    name: "Sega Naomi 2",
    shortName: "Naomi 2",
    extensions: [],
    folderAliases: ["naomi 2", "naomi2", "sega naomi 2"],
    ejsCore: null,
    libretroName: "Sega - Naomi 2",
    color: "#7b1fa2",
  },
  {
    slug: "atomiswave",
    name: "Sammy Atomiswave",
    shortName: "Atomiswave",
    extensions: [],
    folderAliases: ["atomiswave", "sammy atomiswave"],
    ejsCore: null,
    libretroName: "Sammy - Atomiswave",
    color: "#c62828",
  },
  {
    slug: "model2",
    name: "Sega Model 2",
    shortName: "Model 2",
    extensions: [],
    folderAliases: ["model 2", "model2", "sega model 2"],
    ejsCore: null,
    libretroName: "Sega - Model 2",
    color: "#283593",
  },
  {
    slug: "model3",
    name: "Sega Model 3",
    shortName: "Model 3",
    extensions: [],
    folderAliases: ["model 3", "model3", "sega model 3"],
    ejsCore: null,
    libretroName: "Sega - Model 3",
    color: "#1a237e",
  },
  {
    slug: "hikaru",
    name: "Sega Hikaru",
    shortName: "Hikaru",
    extensions: [],
    folderAliases: ["hikaru", "sega hikaru"],
    ejsCore: null,
    libretroName: "Sega - Hikaru",
    color: "#00acc1",
  },
  {
    slug: "triforce",
    name: "Sega Triforce",
    shortName: "Triforce",
    extensions: [],
    folderAliases: ["triforce", "sega triforce"],
    ejsCore: null,
    libretroName: "Sega - Triforce",
    color: "#fdd835",
  },
  {
    slug: "daphne",
    name: "Daphne (LaserDisc Arcade)",
    shortName: "Daphne",
    extensions: [".daphne"],
    folderAliases: ["daphne"],
    ejsCore: null,
    libretroName: "Daphne",
    color: "#f4511e",
  },
  {
    slug: "laserdisc",
    name: "LaserDisc Games",
    shortName: "LaserDisc",
    extensions: [],
    folderAliases: ["laserdisc", "laser disc"],
    ejsCore: null,
    libretroName: "Daphne",
    color: "#ef5350",
  },
  {
    slug: "flash",
    name: "Flash Games",
    shortName: "Flash",
    extensions: [".swf"],
    folderAliases: ["flash", "flash games", "swf"],
    ejsCore: null,
    libretroName: "Flash",
    color: "#d81b60",
  },
  {
    slug: "chailove",
    name: "ChaiLove",
    shortName: "ChaiLove",
    extensions: [".chai", ".chailove"],
    folderAliases: ["chailove"],
    ejsCore: null,
    libretroName: "ChaiLove",
    color: "#f06292",
  },

  // ---- Japanese regional systems (separate from their western siblings) ----
  {
    slug: "famicom",
    name: "Nintendo Famicom",
    shortName: "Famicom",
    extensions: [],
    folderAliases: ["famicom", "fc", "nintendo famicom", "family computer"],
    ejsCore: "nes",
    libretroName: "Nintendo - Nintendo Entertainment System",
    color: "#b71c1c",
  },
  {
    slug: "fds",
    name: "Famicom Disk System",
    shortName: "FDS",
    extensions: [".fds"],
    folderAliases: ["fds", "famicom disk system", "disk system"],
    ejsCore: "nes",
    libretroName: "Nintendo - Family Computer Disk System",
    color: "#c62828",
  },
  {
    slug: "superfamicom",
    name: "Super Famicom",
    shortName: "SFC",
    extensions: [],
    folderAliases: ["super famicom", "sfc", "superfamicom", "nintendo super famicom"],
    ejsCore: "snes",
    libretroName: "Nintendo - Super Nintendo Entertainment System",
    color: "#66594e",
  },
  {
    slug: "megadrive",
    name: "Sega Mega Drive",
    shortName: "MD",
    extensions: [".md"],
    folderAliases: ["mega drive", "megadrive", "md", "sega mega drive"],
    ejsCore: "segaMD",
    libretroName: "Sega - Mega Drive - Genesis",
    color: "#0d47a1",
  },
  {
    slug: "megacd",
    name: "Sega Mega-CD",
    shortName: "Mega-CD",
    extensions: [],
    folderAliases: ["mega cd", "mega-cd", "megacd", "sega mega-cd"],
    ejsCore: "segaCD",
    libretroName: "Sega - Mega-CD - Sega CD",
    color: "#1a237e",
  },
  {
    slug: "mark3",
    name: "Sega Mark III",
    shortName: "Mark III",
    extensions: [],
    folderAliases: ["mark 3", "mark iii", "mark3", "sega mark 3", "sega mark iii"],
    ejsCore: "segaMS",
    libretroName: "Sega - Master System - Mark III",
    color: "#8b0000",
  },
  {
    slug: "pcengine",
    name: "NEC PC Engine",
    shortName: "PCE",
    extensions: [".pce"],
    folderAliases: ["pce", "pc engine", "pcengine", "nec pc engine"],
    ejsCore: "pce",
    libretroName: "NEC - PC Engine - TurboGrafx 16",
    color: "#f57c00",
  },
  {
    slug: "pcenginecd",
    name: "PC Engine CD-ROM²",
    shortName: "PCE-CD",
    extensions: [],
    folderAliases: ["pc engine cd", "pcenginecd", "cd-rom2", "cdrom2", "pce cd", "pc engine-cd", "nec pc engine cd"],
    ejsCore: "pce",
    libretroName: "NEC - PC Engine CD - TurboGrafx-CD",
    color: "#ef6c00",
  },
  {
    slug: "atarist",
    name: "Atari ST",
    shortName: "ST",
    extensions: [".stx", ".msa"],
    folderAliases: ["atari st", "atarist", "st"],
    ejsCore: null,
    libretroName: "Atari - ST",
    color: "#78909c",
  },
  {
    slug: "jaguarcd",
    name: "Atari Jaguar CD",
    shortName: "Jag CD",
    extensions: [],
    folderAliases: ["jaguar cd", "jaguarcd", "atari jaguar cd"],
    ejsCore: null,
    libretroName: "Atari - Jaguar",
    color: "#880e4f",
  },
  {
    slug: "gx4000",
    name: "Amstrad GX4000",
    shortName: "GX4000",
    extensions: [],
    folderAliases: ["gx4000", "gx 4000", "amstrad gx4000"],
    ejsCore: null,
    libretroName: "Amstrad - GX4000",
    color: "#00838f",
  },
  {
    slug: "cd32",
    name: "Commodore Amiga CD32",
    shortName: "CD32",
    extensions: [],
    folderAliases: ["cd32", "amiga cd32", "commodore amiga cd32"],
    ejsCore: null,
    libretroName: "Commodore - CD32",
    color: "#d84315",
  },
  {
    slug: "camplynx",
    name: "Camputers Lynx",
    shortName: "CampLynx",
    extensions: [],
    folderAliases: ["camputers lynx", "camputers"],
    ejsCore: null,
    libretroName: "Camputers - Lynx",
    color: "#33691e",
  },
  {
    slug: "msx2",
    name: "MSX2",
    shortName: "MSX2",
    extensions: [],
    folderAliases: ["msx2", "msx 2", "msx2+", "microsoft msx2"],
    ejsCore: null,
    libretroName: "Microsoft - MSX2",
    color: "#006064",
  },
];

/** Extensions that need a folder hint to resolve (archives, disc images) */
// .chd (MAME Compressed Hunks of Data) is a single self-describing disc image
// used across many CD-based systems (PS1, Saturn, Sega/Mega-CD, PC Engine CD,
// 3DO, Neo Geo CD, arcade…), so — like .iso/.bin — the owning system is decided
// by the containing folder, not the extension. CHD-capable cores read it as-is,
// which is the whole point: no chdman/BIN+CUE step, and less I/O than raw discs.
export const AMBIGUOUS_EXTENSIONS = [".zip", ".7z", ".bin", ".cue", ".iso", ".rom", ".chd"];

/** Manufacturer/vendor per system, used for grouping and sort order */
export const VENDOR_BY_SLUG: Record<string, string> = {
  // Nintendo
  nes: "Nintendo", snes: "Nintendo", n64: "Nintendo", gb: "Nintendo", gbc: "Nintendo",
  gba: "Nintendo", nds: "Nintendo", vb: "Nintendo", "3ds": "Nintendo", gamecube: "Nintendo",
  wii: "Nintendo", wiiu: "Nintendo", switch: "Nintendo", gandw: "Nintendo",
  famicom: "Nintendo", fds: "Nintendo", superfamicom: "Nintendo", satellaview: "Nintendo",
  sufami: "Nintendo", n64dd: "Nintendo", pokemini: "Nintendo", wiiware: "Nintendo",
  // Sega
  genesis: "Sega", sms: "Sega", gg: "Sega", segacd: "Sega", sega32x: "Sega",
  saturn: "Sega", dreamcast: "Sega", sg1000: "Sega", segapico: "Sega",
  naomi: "Sega", naomi2: "Sega", hikaru: "Sega", model2: "Sega", model3: "Sega",
  triforce: "Sega", megadrive: "Sega", megacd: "Sega", mark3: "Sega",
  // Sony
  psx: "Sony", ps2: "Sony", ps3: "Sony", psp: "Sony", vita: "Sony",
  // Microsoft
  xbox: "Microsoft", xbox360: "Microsoft", msx: "Microsoft", msx2: "Microsoft", dos: "Microsoft",
  // Atari
  atari2600: "Atari", atari5200: "Atari", atari7800: "Atari", lynx: "Atari",
  jaguar: "Atari", atari800: "Atari", atarist: "Atari", jaguarcd: "Atari",
  // NEC
  pce: "NEC", pcecd: "NEC", pcfx: "NEC", supergrafx: "NEC",
  pcengine: "NEC", pcenginecd: "NEC",
  // SNK
  neogeo: "SNK", ngp: "SNK",
  // Others (alphabetical vendors)
  archimedes: "Acorn", bbcmicro: "Acorn", electron: "Acorn",
  acpc: "Amstrad", gx4000: "Amstrad",
  appleii: "Apple",
  camplynx: "Camputers",
  arcade: "Arcade", daphne: "Arcade", laserdisc: "Arcade",
  atomiswave: "Sammy",
  astrocade: "Bally",
  wonderswan: "Bandai", supervision8000: "Bandai",
  pv1000: "Casio", pv2000: "Casio",
  coleco: "Coleco",
  c64: "Commodore", amiga: "Commodore", vic20: "Commodore",
  cdtv: "Commodore", maxmachine: "Commodore", cd32: "Commodore",
  megaduck: "Creatronic",
  arcadia2001: "Emerson",
  adventurevision: "Entex",
  gamepocket: "Epoch", scv: "Epoch",
  exidysorcerer: "Exidy",
  channelf: "Fairchild",
  vectrex: "GCE",
  vc4000: "Interton",
  odyssey2: "Magnavox",
  intellivision: "Mattel",
  ouya: "Ouya",
  "3do": "Panasonic",
  cdi: "Philips", vg5000: "Philips",
  zxspectrum: "Sinclair",
  chailove: "Other", flash: "Other", mikrosha: "Other",
};

export function platformVendor(slug: string): string {
  return VENDOR_BY_SLUG[slug] ?? "Other";
}

/** Playable: has an EmulatorJS core, or Flash via Ruffle */
export function platformPlayable(p: Pick<Platform, "slug" | "ejsCore">): boolean {
  return !!p.ejsCore || p.slug === "flash";
}

/** Japan-market systems — their libraries are Japanese by nature, so the
 *  system page language filter defaults to "all" instead of English. */
export const JAPANESE_SYSTEMS = new Set([
  "famicom",
  "fds",
  "superfamicom",
  "megadrive",
  "megacd",
  "mark3",
  "pcengine",
  "pcenginecd",
  "supergrafx",
  "sg1000",
  "pcfx",
  "wonderswan",
  "wonderswancolor",
  "msx",
  "msx2",
]);

/** All platforms sorted alphabetically by vendor, then by system name */
export const PLATFORMS_SORTED: Platform[] = [...PLATFORMS].sort((a, b) => {
  const va = platformVendor(a.slug);
  const vb = platformVendor(b.slug);
  return va === vb ? a.name.localeCompare(b.name) : va.localeCompare(vb);
});

/** Slugs of folder-based platforms (an extracted Wii U title, etc.) — a ROM is
 *  a directory, not a single file. Callers that stream file bytes (hashing)
 *  must skip these. */
export const FOLDER_ROM_SLUGS: string[] = PLATFORMS.filter((p) => p.folderRom).map((p) => p.slug);

const bySlug = new Map(PLATFORMS.map((p) => [p.slug, p]));
const byExtension = new Map<string, Platform>();
for (const p of PLATFORMS) for (const ext of p.extensions) byExtension.set(ext, p);
// libretroName is exactly the libretro-database DAT filename (sans .dat), so it
// maps DAT files onto our slugs directly. Several platforms share a name (e.g.
// two arcade entries) — first definition wins.
const byLibretroName = new Map<string, Platform>();
for (const p of PLATFORMS) if (!byLibretroName.has(p.libretroName)) byLibretroName.set(p.libretroName, p);

export function platformBySlug(slug: string): Platform | undefined {
  return bySlug.get(slug);
}

export function platformByExtension(ext: string): Platform | undefined {
  return byExtension.get(ext.toLowerCase());
}

/** Resolve a platform from a folder name (e.g. "SNES", "Mega Drive") */
export function platformByFolder(folderName: string): Platform | undefined {
  const needle = folderName.toLowerCase().trim();
  return PLATFORMS.find(
    (p) => p.folderAliases.includes(needle) || p.name.toLowerCase() === needle
  );
}

/** Resolve a platform from a libretro-database system name (== DAT filename
 *  without the .dat extension, e.g. "Nintendo - Nintendo Entertainment System") */
export function platformByLibretroName(name: string): Platform | undefined {
  return byLibretroName.get(name.trim());
}
