"use client";

// GameHub UI sounds (served from /public/sounds) — original synthesized
// effects generated by scripts/gen-sounds.mjs (public domain / CC0).
// Client-only; respects the "UI sounds" toggle in Quick Access.
//
// AudioLoader support: every event also maps to the canonical SteamOS sound
// filename (steamui/sounds/deck_ui_*.wav) that deckthemes audio packs ship.
// When a sound pack is active (window.__GH_AUDIO, set by AudioManager),
// resolution mirrors AudioLoader's PlayAudioURL patch: `ignore` keeps the
// default, `mappings` picks a random alternative, otherwise the path is
// replaced with /sounds_custom/<packDir>/<canonical>. If a pack lacks the
// file, we fall back to the default sound (a real Deck falls back to
// silence — a broken pack shouldn't mute a web app).

const FILES = {
  navigate: "nav-tick.wav",
  activate: "select.wav",
  back: "close.wav",
  intoGame: "zoom-in.wav",
  outOfGame: "zoom-out.wav",
  launch: "launch.wav",
  menuOpen: "slide-in.wav",
  menuClose: "slide-out.wav",
  modalOpen: "open.wav",
  modalClose: "close.wav",
  toggleOn: "toggle-on.wav",
  toggleOff: "toggle-off.wav",
  tab: "tab.wav",
  keyType: "key-type.wav",
  toast: "notify.wav",
  bumperEnd: "bump.wav",
  startup: "startup.wav",
  confirm: "confirm.wav",
} as const;

/** Canonical SteamOS sound files (what audio packs name their replacements) */
const STEAM_FILES: Partial<Record<SoundName, string>> = {
  navigate: "deck_ui_navigation.wav",
  activate: "deck_ui_default_activation.wav",
  back: "deck_ui_hide_modal.wav",
  intoGame: "deck_ui_into_game_detail.wav",
  outOfGame: "deck_ui_out_of_game_detail.wav",
  launch: "deck_ui_launch_game.wav",
  menuOpen: "deck_ui_side_menu_fly_in.wav",
  menuClose: "deck_ui_side_menu_fly_out.wav",
  modalOpen: "deck_ui_show_modal.wav",
  modalClose: "deck_ui_hide_modal.wav",
  toggleOn: "deck_ui_switch_toggle_on.wav",
  toggleOff: "deck_ui_switch_toggle_off.wav",
  tab: "deck_ui_tab_transition_01.wav",
  keyType: "deck_ui_typing.wav",
  toast: "deck_ui_message_toast.wav",
  bumperEnd: "deck_ui_bumper_end_02.wav",
  confirm: "deck_ui_achievement_toast.wav",
  // "startup" has no SteamOS equivalent (boot audio is baked into the
  // startup movie) — always plays GameHub's own file
};

export type SoundName = keyof typeof FILES;

const VOLUMES: Partial<Record<SoundName, number>> = {
  navigate: 0.35,
  activate: 0.5,
  tab: 0.4,
  keyType: 0.4,
  startup: 0.6,
  launch: 0.6,
};

export interface ActiveAudio {
  sound: { dir: string; ignore: string[]; mappings: Record<string, string[]> } | null;
  soundVolume: number;
}

declare global {
  interface Window {
    __GH_AUDIO?: ActiveAudio;
  }
}

/** Resolve an event to its URL through the active sound pack. */
function resolveSoundUrl(name: SoundName): { url: string; fallback: string } {
  const fallback = `/sounds/${FILES[name]}`;
  const active = typeof window !== "undefined" ? window.__GH_AUDIO : undefined;
  const canonical = STEAM_FILES[name];
  const pack = active?.sound;
  if (!pack || !canonical) return { url: fallback, fallback };
  if (pack.ignore.includes(canonical)) return { url: fallback, fallback };
  const mapped = pack.mappings[canonical];
  if (Array.isArray(mapped) && mapped.length > 0) {
    const pick = mapped[Math.trunc(Math.random() * mapped.length)];
    return { url: `/sounds_custom/${pack.dir}/${pick}`, fallback };
  }
  return { url: `/sounds_custom/${pack.dir}/${canonical}`, fallback };
}

const cache = new Map<string, HTMLAudioElement>();

export function soundsEnabled(): boolean {
  if (typeof window === "undefined") return false;
  return localStorage.getItem("gh-sounds") !== "off";
}

export function setSoundsEnabled(on: boolean) {
  localStorage.setItem("gh-sounds", on ? "on" : "off");
}

/** Game theme music on game pages — separate toggle from UI sounds */
export function themeMusicEnabled(): boolean {
  if (typeof window === "undefined") return false;
  return localStorage.getItem("gh-theme-music") !== "off";
}

export function setThemeMusicEnabled(on: boolean) {
  localStorage.setItem("gh-theme-music", on ? "on" : "off");
  window.dispatchEvent(new CustomEvent("gh-thememusic", { detail: { on } }));
}

/** User-set UI-sound volume (0..1), layered on top of the sound pack's own
 *  volume. Cached so playSound doesn't hit localStorage on every event. */
let _userVolume: number | null = null;
export function soundVolume(): number {
  if (typeof window === "undefined") return 1;
  if (_userVolume == null) {
    const v = parseFloat(localStorage.getItem("gh-sound-volume") ?? "1");
    _userVolume = Number.isFinite(v) ? Math.min(1, Math.max(0, v)) : 1;
  }
  return _userVolume;
}
export function setSoundVolume(v: number) {
  _userVolume = Math.min(1, Math.max(0, v));
  localStorage.setItem("gh-sound-volume", String(_userVolume));
}

/** Warm the cache so time-critical sounds (back-before-navigation) play */
export function preloadSounds(names: SoundName[]) {
  if (typeof window === "undefined") return;
  for (const name of names) {
    const { url } = resolveSoundUrl(name);
    if (cache.has(url)) continue;
    try {
      const audio = new Audio(url);
      audio.preload = "auto";
      cache.set(url, audio);
    } catch {}
  }
}

export function playSound(name: SoundName) {
  if (typeof window === "undefined" || !soundsEnabled()) return;
  try {
    const { url, fallback } = resolveSoundUrl(name);
    const volume =
      (VOLUMES[name] ?? 0.5) * (window.__GH_AUDIO?.soundVolume ?? 1) * soundVolume();
    let audio = cache.get(url);
    if (!audio) {
      audio = new Audio(url);
      if (url !== fallback) {
        // pack file missing → fall back to the default sound once
        audio.addEventListener("error", () => {
          cache.delete(url);
          const alt = new Audio(fallback);
          alt.volume = volume;
          void alt.play().catch(() => {});
        });
      }
      cache.set(url, audio);
    }
    audio.volume = volume;
    audio.currentTime = 0;
    void audio.play().catch(() => {});
  } catch {
    // audio not available — never break the UI over a sound
  }
}
