const en = require('./src/messages/en.json');
const pt = require('./src/messages/pt.json');
const fs = require('fs');

// Comprehensive Portuguese translations for all in-scope keys
const translations = {
  romProperties: {
    "titleLabel": "Título",
    "systemLabel": "Sistema",
    "systemDesc": "Altera qual núcleo de emulador é usado.",
    "regionLabel": "Região",
    "regionPlaceholder": "EUA",
    "boxartUrlLabel": "URL da capa",
    "boxartUrlDesc": "Deixe vazio para usar uma capa gerada.",
    "urlPlaceholder": "https://…",
    "matchFilenameLabel": "Corresponder ao nome do arquivo",
    "matchFilenameDesc": "Atualizar apenas o título personalizado — tudo mais vem de uma correspondência de metadados",
    "matchButton": "Corresponder",
    "matchTitleLabel": "Procurar por",
    "matchTitleDesc": "Buscar manualmente no banco de dados do provedor",
    "heroUrlLabel": "URL da imagem hero",
    "heroUrlDesc": "Deixe vazio para remover.",
    "iconUrlLabel": "URL do ícone",
    "iconUrlDesc": "Deixe vazio para remover.",
    "boxartPreviewAlt": "Pré-visualização: {title}",
    "noImageAtUrl": "Nenhuma imagem nesse URL",
    "generatedCover": "Capa gerada",
    "mediaIntro": "Mídia personalizada",
    "chooseFile": "Escolher arquivo…",
    "themeMusicYoutube": "Tema sonoro (YouTube)",
    "themeDescFile": "Arquivo enviado",
    "themeDescYt": "Reproduzindo do YouTube",
    "themeDescNone": "Nenhum",
    "youtubePlaceholder": "ID do vídeo ou URL",
    "setVideo": "Definir vídeo",
    "reSearch": "Pesquisar novamente",
    "removeUploadedFile": "Remover arquivo enviado",
    "scrapeMetadataLabel": "Metadados",
    "lastScraped": "Coletado pela última vez",
    "scrapeDesc": "Clique para atualizar este jogo com a versão mais recente dos metadados do provedor",
    "releaseDatePlaceholder": "AAAA-MM-DD ou ano",
    "playersLabel": "Jogadores",
    "playersPlaceholder": "ex.: 1-4",
    "languagesLabel": "Idiomas",
    "languagesPlaceholder": "ex.: Inglês, Português",
    "descriptionLabel": "Descrição",
    "filenameLabel": "Nome do arquivo",
    "renameDesc": "Renomear para corresponder ao banco de dados do provedor. Isto quebra caminhos salvos e variantes.",
    "renameButton": "Renomear arquivo",
    "pathLabel": "Caminho",
    "sizeLabel": "Tamanho",
    "addedLabel": "Adicionado",
    "dangerZone": "Zona de perigo",
    "dangerIntro": "Estas ações afetam apenas este jogo.",
    "dangerDeleteFile": "Excluir arquivo de ROM",
    "dangerKeepFile": "Manter arquivo",
    "alsoDeleteFile": "Também excluir o arquivo de ROM do disco",
    "heading": "Propriedades do ROM",
    "title": "ROM — {title}",
    "gameTitle": "Título do jogo",
    "gameTitlePlaceholder": "Título personalizado",
    "path": "Caminho",
    "filename": "Nome do arquivo",
    "size": "Tamanho",
    "crc": "CRC",
    "md5": "MD5",
    "sha1": "SHA1",
    "releaseYear": "Ano de lançamento",
    "releaseYearPlaceholder": "AAAA",
    "developer": "Desenvolvedora",
    "publisher": "Distribuidora",
    "description": "Descrição",
    "descriptionPlaceholder": "Descrição do jogo",
    "genre": "Gênero",
    "genrePlaceholder": "ex.: Ação, Aventura",
    "modes": "Modos",
    "modesPlaceholder": "ex.: Um jogador, Multijogador",
    "themes": "Temas",
    "themesPlaceholder": "ex.: Ficção científica, Fantasia",
    "franchise": "Franquia",
    "franchisePlaceholder": "ex.: Mario, Zelda",
    "region": "Região",
    "language": "Idioma",
    "rating": "Classificação",
    "ratingPlaceholder": "ex.: T for Teen",
    "variant": "Variante",
    "variantPlaceholder": "ex.: Hack, Tradução",
    "playStatus": "Status do jogo",
    "statusNeverPlayed": "Nunca jogado",
    "statusBacklog": "Em espera",
    "statusPlaying": "Jogando",
    "statusBeaten": "Completado",
    "statusDropped": "Abandonado",
    "favorite": "Favorito",
    "personalRating": "Avaliação pessoal",
    "difficulty": "Dificuldade",
    "completion": "Conclusão",
    "difficultyNotSet": "Não definida",
    "completionNotSet": "Não definida",
    "saveFile": "Arquivo de save",
    "saveFileBytes": "{size} bytes",
    "lastModified": "Última modificação",
    "cannotBeChanged": "Não pode ser alterado",
    "cancel": "Cancelar",
    "save": "Salvar",
    "saving": "Salvando…",
    "saveFailed": "Falha ao salvar",
    "searchingForMatch": "Procurando correspondência…",
    "matchHelp": "Clique em um resultado para atualizar este jogo com seus metadados e arte",
    "noMatches": "Nenhuma correspondência encontrada",
    "ratingLabel": "Classificação",
    "languageLabel": "Idioma",
    "releaseDateLabel": "Data de lançamento",
    "developerLabel": "Desenvolvedora",
    "publisherLabel": "Distribuidora",
    "genreLabel": "Gênero",
    "franchiseLabel": "Franquia",
    "themesLabel": "Temas",
    "modesLabel": "Modos",
    "hltbEstimate": "HowLongToBeat",
    "mainStory": "História principal",
    "mainExtra": "Principal + Extra",
    "completionist": "Completista",
    "notFound": "Não encontrado"
  },

  systemTools: {
    "scanning": "Escaneando {name}…",
    "scanStarted": "Escaneamento iniciado — veja o cabeçalho ou página de downloads",
    "scanFailed": "Falha ao iniciar o escaneamento",
    "scrapeStartFailed": "Falha ao iniciar a coleta",
    "scrapeQueued": "Na fila atrás do trabalho atual — acompanhe na página de downloads.",
    "scrapeStarted": "Coleta de {name} iniciada — veja o cabeçalho ou página de downloads.",
    "cleanupCheckFailed": "Falha na verificação de limpeza",
    "nothingToClean": "Nada para limpar — nenhum jogo de {name} marcado como ausente.",
    "metadataAssociationFailed": "Falha ao associar metadados",
    "failedToFetch": "Falha ao buscar",
    "failedAssociateMetadata": "Falha ao associar metadados com {name}",
    "selectOutcome": "Selecione um resultado para usar seus metadados",
    "imageResolution": "Resolução: {width}×{height}",
    "selectImage": "Selecionar",
    "deleteImage": "Excluir",
    "uploadingMedia": "Enviando mídia…",
    "uploadFailed": "Falha no envio",
    "uploadedTitle": "✓ Enviado: {name}",
    "generatingCover": "Gerando capa…",
    "generatingCoverFailed": "Falha ao gerar capa",
    "generatedTitle": "✓ Capa gerada",
    "uploading": "Enviando…",
    "failed": "Falhou",
    "clearingAll": "Limpando tudo…",
    "allCleared": "✓ Tudo limpo",
    "removingAll": "Removendo tudo…",
    "allRemoved": "✓ Tudo removido",
    "removingFile": "Removendo arquivo…",
    "fileRemoved": "✓ Arquivo removido",
    "renamingFile": "Renomeando arquivo…",
    "renamed": "✓ Renomeado para {name}",
    "renameFailed": "Falha ao renomear",
    "selectGame": "Selecionar jogo",
    "fetchingMetadata": "Buscando metadados…",
    "deletingFromDisk": "Excluindo do disco…",
    "deletedFromDisk": "✓ Excluído do disco",
    "unscrappedHint": "Este jogo ainda não foi coletado. Clique em qualquer resultado para associar seus metadados.",
    "scrapingAs": "Coletando como \"{name}\"…",
    "scrapedTitle": "Coletado",
    "nothingFound": "Nada encontrado",
    "systemTools": "Ferramentas de {name}",
    "rescanFiles": "Reescanear arquivos",
    "rescanFilesDesc": "Procurar novos arquivos e marcar como ausentes os removidos",
    "scrapeMissing": "Coletar ausentes",
    "scrapeMissingDesc": "Buscar arte e detalhes apenas dos jogos que ainda não têm nenhum",
    "scrapeAll": "Coletar tudo",
    "scrapeAllDesc": "Rebuscar arte e detalhes de todos os jogos deste sistema",
    "backfillMetadata": "Preencher metadados (sem arte)",
    "backfillMetadataDesc": "Preencher apenas campos de texto ausentes + trailer e jogos relacionados do IGDB — nunca sobrescreve dados existentes",
    "chooseHero": "Escolher imagem hero…",
    "chooseLogo": "Escolher logo…",
    "chooseIcon": "Escolher ícone…",
    "autoFetchAll": "Buscar toda a arte automaticamente",
    "updateSystemInfo": "Atualizar informações do sistema",
    "updateSystemInfoDesc": "Buscar nome, descrição, desenvolvedor e logotipo do provedor de metadados configurado",
    "cardShape": "Formato do cartão",
    "cardShapeDesc": "Alterar aparência visual — auto segue a relação de aspecto da capa de cada jogo",
    "cardShapeAuto": "Auto",
    "cardShapeDefault": "Padrão (4:3)",
    "cardShapeWide": "Largo (16:9)",
    "cleanupMissing": "Limpar ausentes…",
    "removeMissing": "{count, plural, one {Remover # jogo ausente?} other {Remover # jogos ausentes?}}",
    "removed": "{count, plural, one {✓ Removido # jogo} other {✓ Removidos # jogos}}",
    "remove": "Remover",
    "rescan": "Reescanear",
    "rescanDesc": "Procurar novos arquivos e marcar como ausentes os removidos",
    "scrapeMissingLabel": "Coletar ausentes",
    "scrapeEverything": "Coletar tudo",
    "backfillMetadataLabel": "Preencher metadados (sem arte)",
    "sectionArtwork": "Arte",
    "heroImageMenu": "Imagem hero do sistema…",
    "logoMenu": "Logo do sistema…",
    "iconMenu": "Ícone do sistema…",
    "sectionSystem": "Sistema",
    "cardShapeLabel": "Formato do cartão",
    "autoLabel": "Auto",
    "searchingProviders": "Buscando nos provedores configurados…",
    "noArtFound": "Nenhum {label} encontrado",
    "turningOff": "Desativando…",
    "downloading": "Baixando…",
    "clearing": "Limpando…",
    "applying": "Aplicando…",
    "fetchingSystemArtwork": "Buscando arte do sistema nos provedores…",
    "updatedSystem": "✓ Sistema atualizado {items}",
    "noNewSystemArtwork": "Nenhuma arte nova do sistema encontrada",
    "couldntFetchSystemArtwork": "Não foi possível buscar a arte do sistema",
    "startingScan": "Iniciando escaneamento…",
    "couldntStartScan": "✗ Não foi possível iniciar o escaneamento",
    "startingScrape": "Iniciando coleta…",
    "couldntStartScrape": "✗ Não foi possível iniciar a coleta",
    "fetchingSystemInfo": "Buscando informações do sistema…",
    "systemInfoUpdated": "✓ Informações do sistema atualizadas",
    "noInfoFound": "Nenhuma informação encontrada",
    "updatingCardShape": "Atualizando formato do cartão…",
    "cardShapeSet": "✓ Formato do cartão: {shape}",
    "autoWithValue": "Auto ({value})",
    "defaultLayout": "padrão",
    "nothingToClean": "Nada para limpar — nenhum jogo de {name} ausente.",
    "cleanupCheckFailed": "Falha na verificação de limpeza",
    "removedGames": "{count, plural, one {✓ Removido # jogo} other {✓ Removidos # jogos}}",
    "cleanupFailed": "✗ Falha na limpeza"
  },

  scraperOptions: {
    "title": "Opções de coleta",
    "saved": "Salvo",
    "intro": "Escolha qual provedor vence quando ambos têm o mesmo item, e quais itens coletar.",
    "providerPriority": "Prioridade do provedor",
    "ready": "Pronto",
    "notConfigured": "Não configurado — ignorado",
    "moveUp": "Mover {name} para cima",
    "moveDown": "Mover {name} para baixo",
    "itemsToScrape": "Itens para coletar",
    "via": "via {names}",
    "none": "Nenhum",
    "all": "Todos",
    "selectNone": "Desselecionar tudo",
    "selectAll": "Selecionar tudo"
  },

  emulator: {
    "stateSaved": "Estado salvo no GameHub",
    "saveFailed": "Falha ao salvar",
    "noSavedStates": "Nenhum estado salvo ainda",
    "stateLoaded": "Estado carregado",
    "loadFailed": "Falha ao carregar",
    "resumedSaveState": "Estado salvo retomado",
    "loadEmulatorError": "Não foi possível carregar o emulador. Verifique sua conexão e tente novamente.",
    "loadTimeoutError": "Isto está demorando mais do que o esperado. O jogo ou núcleo pode estar indisponível.",
    "controllerLayout": "Layout do controle",
    "exitToGame": "Sair para o jogo",
    "batterySaveLoaded": "Save de bateria carregado do GameHub",
    "startingGame": "Iniciando {title}",
    "loadingCoreGame": "{platformName} · carregando núcleo e jogo…",
    "cancel": "Cancelar",
    "couldntStartGame": "Não foi possível iniciar o jogo",
    "retry": "Tentar novamente",
    "exit": "Sair",
    "dismiss": "Descartar",
    "controllerLayoutTitle": "Layout do controle — {title}"
  },

  home: {
    "readMore": "Ler mais ↗",
    "viewMore": "Ver mais →",
    "recentGames": "Jogos recentes",
    "newToLibrary": "Novo na biblioteca",
    "playtime": "Tempo de jogo: {time}",
    "neverPlayed": "Nunca jogado",
    "viewMoreLibrary": "Ver mais na sua Biblioteca",
    "tabNew": "Novidades",
    "tabFriends": "Amigos",
    "tabRecommended": "Recomendado",
    "nothingNew": "Nada de novo ainda.",
    "newToYourLibrary": "Novo na sua biblioteca",
    "joinedCollection": "{title} entrou na sua coleção",
    "activity": "Atividade",
    "noActivity": "Nenhuma atividade de outros jogadores ainda.",
    "played": "jogou",
    "nothingToRecommend": "Nada para recomendar ainda — adicione e jogue mais jogos para construir suas escolhas."
  },

  mobileHome: {
    "greeting": "Olá {userName} 👋",
    "jumpBackIn": "Volte para onde parou",
    "tabNew": "Novidades",
    "tabFriends": "Amigos",
    "tabRecommended": "Recomendado",
    "newToLibrary": "Novo na sua biblioteca",
    "seeAll": "Ver tudo",
    "nothingNew": "Nada de novo por enquanto.",
    "noActivity": "Sem atividade recente ainda — jogue algo para começar.",
    "noRecommended": "Jogue e colete alguns jogos e as sugestões personalizadas aparecerão aqui."
  },

  mobileDownloads: {
    "library": "Biblioteca",
    "nowScraping": "Coletando agora · {current}",
    "scrapingMetadata": "Coletando metadados…",
    "scanningFiles": "Escaneando arquivos…",
    "throughput": "Taxa",
    "peak": "Pico",
    "systems": "Sistemas",
    "parallel": "Paralelo",
    "perMin": "{value}/min",
    "cancel": "Cancelar",
    "scanningFilesBar": "Escaneando arquivos",
    "scrapingMetadataBar": "Coletando metadados",
    "unitSystems": "sistemas",
    "unitGames": "jogos",
    "currentSystem": "Sistema atual — {name}",
    "quotaPaused": "Pausado — um provedor atingiu seu limite de requisições. Retoma quando a janela redefinir.",
    "upNext": "A seguir",
    "nothingQueued": "Nada na fila para rodar em seguida.",
    "sysGamesProgress": "{done} / {total} jogos",
    "queued": "na fila",
    "next": "Próximo",
    "queuedLabel": "Na fila",
    "nothingRunning": "Nada em execução no momento — escaneamentos e coletas aparecem aqui, e qualquer coisa esperando aparece em Agendado.",
    "loading": "Carregando…",
    "scheduled": "Agendado",
    "noRecurringTasks": "Nenhuma tarefa recorrente ativada.",
    "auto": "Auto"
  },

  primitives: {
    "cancel": "Cancelar",
    "confirm": "Confirmar"
  }
};

// Merge translations
let result = JSON.parse(JSON.stringify(pt));
let translatedCount = 0;

const inScope = ['romProperties', 'systemTools', 'settingsSysKb', 'scraperOptions', 'collectionsComps', 'fileModals', 'mobileSettings', 'collectionsPages', 'mobileDownloads', 'emulator', 'home', 'mobileHome', 'mobileNav', 'mobileMisc', 'accessibility', 'primitives'];

inScope.forEach(ns => {
  if (!result[ns]) {
    result[ns] = {};
  }

  if (en[ns]) {
    Object.keys(en[ns]).forEach(key => {
      if (!(key in result[ns])) {
        if (translations[ns] && translations[ns][key]) {
          result[ns][key] = translations[ns][key];
          translatedCount++;
        } else {
          result[ns][key] = en[ns][key];
        }
      }
    });
  }
});

fs.writeFileSync('./src/messages/pt.json', JSON.stringify(result, null, 2));
console.log(`✓ Updated pt.json with comprehensive Portuguese translations`);
console.log(`Added ${translatedCount} properly translated keys`);
