"use client";

// Collections page body with a Grid / List view toggle (persisted per-device),
// mirroring the Systems page. Grid = the store-category collage tiles; List =
// a compact one-line-per-collection view that's faster to scan. The header
// carries the title, the toggle, and the "New collection" action.

import Link from "next/link";
import { Fragment, useEffect, useState, type ReactNode } from "react";
import { useTranslations } from "next-intl";
import CategoryTile from "@/components/CategoryTile";
import { playSound } from "@/lib/sounds";

export interface CollectionCardData {
  id: number;
  name: string;
  count: number;
  covers: string[];
  isOwn: boolean;
  ownerName: string;
  isSmart: boolean;
  isPublic: boolean;
}

/** Auto-generated groupings (Genres / Developers / Publishers). */
export interface DimensionSection {
  key: string; // "genre" | "developer" | "publisher"
  label: string;
  entries: { value: string; count: number; covers: string[] }[];
}

const VIEW_KEY = "gh-collections-view";

export default function CollectionsView({
  title,
  collections,
  dimensions = [],
  autoGeneratedNote,
  emptyVirtualNote,
  actions,
}: {
  title: string;
  collections: CollectionCardData[];
  /** Virtual dimension sections, rendered below the user collections and
   *  following the same grid/list toggle. */
  dimensions?: DimensionSection[];
  autoGeneratedNote?: string;
  emptyVirtualNote?: string;
  /** The "New collection" button (rendered in the header, next to the toggle). */
  actions?: ReactNode;
}) {
  const t = useTranslations("collectionsPages.index");
  const tv = useTranslations("systemsView.view");
  const [view, setView] = useState<"grid" | "list">("grid");
  useEffect(() => {
    const saved = localStorage.getItem(VIEW_KEY);
    if (saved === "list" || saved === "grid") setView(saved);
  }, []);

  function choose(v: "grid" | "list") {
    playSound("tab");
    setView(v);
    localStorage.setItem(VIEW_KEY, v);
  }

  return (
    <>
      <div className="mb-6 flex flex-wrap items-center justify-between gap-4">
        <h1 className="text-2xl font-black text-bright">{title}</h1>
        <div className="flex items-center gap-3">
          {(collections.length > 0 || dimensions.some((d) => d.entries.length > 0)) && (
            <div key="view-toggle" className="flex items-center gap-1 rounded-[4px] bg-[#1a1f27] p-1 ring-1 ring-white/10">
              {(["grid", "list"] as const).map((v) => (
                <button
                  key={v}
                  onClick={() => choose(v)}
                  aria-label={v === "grid" ? tv("gridViewAria") : tv("listViewAria")}
                  aria-pressed={view === v}
                  className={`Focusable flex h-8 w-9 cursor-pointer items-center justify-center rounded-[3px] transition-colors ${
                    view === v ? "bg-[#3d4450] text-bright" : "text-dim hover:text-bright"
                  }`}
                >
                  {v === "grid" ? (
                    <svg viewBox="0 0 24 24" fill="currentColor" className="h-4 w-4">
                      <rect x="3" y="3" width="8" height="8" rx="1" /><rect x="13" y="3" width="8" height="8" rx="1" />
                      <rect x="3" y="13" width="8" height="8" rx="1" /><rect x="13" y="13" width="8" height="8" rx="1" />
                    </svg>
                  ) : (
                    <svg viewBox="0 0 24 24" fill="currentColor" className="h-4 w-4">
                      <rect x="3" y="4" width="18" height="3" rx="1" /><rect x="3" y="10.5" width="18" height="3" rx="1" />
                      <rect x="3" y="17" width="18" height="3" rx="1" />
                    </svg>
                  )}
                </button>
              ))}
            </div>
          )}
          {actions && <Fragment key="actions">{actions}</Fragment>}
        </div>
      </div>

      {collections.length === 0 ? (
        <p className="py-16 text-center text-dim">{t("empty")}</p>
      ) : view === "list" ? (
        <div className="flex flex-col gap-1.5">
          {collections.map((c) => (
            <Link
              key={c.id}
              href={`/collections/${c.id}`}
              className="deck-card group flex items-center gap-3 rounded-[4px] bg-[#23262e] px-4 py-2.5 transition-colors hover:bg-[#2b2f38]"
              title={c.name}
            >
              <span className="min-w-0 flex-1 truncate text-[15px] font-semibold text-bright">{c.name}</span>
              {c.isSmart && (
                <span className="shrink-0 rounded bg-white/10 px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wider text-dim" title={t("smartTitle")}>
                  {t("smartBadge")}
                </span>
              )}
              {c.isPublic && (
                <span className="shrink-0 rounded bg-white/10 px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wider text-dim">
                  {t("publicBadge")}
                </span>
              )}
              {!c.isOwn && (
                <span className="hidden shrink-0 truncate text-[12px] text-dim sm:block">{t("byOwner", { name: c.ownerName })}</span>
              )}
              <span className="w-24 shrink-0 text-right text-[13px] tabular-nums text-dim">{tv("gameCount", { count: c.count })}</span>
            </Link>
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">
          {collections.map((c) => (
            <CategoryTile
              key={c.id}
              href={`/collections/${c.id}`}
              name={c.name}
              count={c.count}
              covers={c.covers}
              subtitle={!c.isOwn ? t("byOwner", { name: c.ownerName }) : undefined}
              badges={
                <>
                  {c.isSmart && (
                    <span className="rounded bg-black/45 px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wider text-white backdrop-blur-sm" title={t("smartTitle")}>
                      {t("smartBadge")}
                    </span>
                  )}
                  {c.isPublic && (
                    <span className="rounded bg-black/45 px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wider text-white backdrop-blur-sm">
                      {t("publicBadge")}
                    </span>
                  )}
                </>
              }
            />
          ))}
        </div>
      )}

      {/* Auto-generated groupings (Genres / Developers / Publishers) — same
          store-category tiles, and the same grid/list toggle as above. */}
      {dimensions.some((d) => d.entries.length > 0) && autoGeneratedNote && (
        <p className="mt-10 text-sm text-dim">{autoGeneratedNote}</p>
      )}
      {dimensions.map((d) =>
        d.entries.length === 0 ? null : (
          <section key={d.key}>
            <h2 className="mb-4 mt-10 text-[22px] font-bold text-bright">
              {d.label} <span className="ml-1 align-middle text-sm font-semibold text-dim">{d.entries.length}</span>
            </h2>
            {view === "list" ? (
              <div className="flex flex-col gap-1.5">
                {d.entries.map((e) => (
                  <Link
                    key={e.value}
                    href={`/collections/virtual/${d.key}/${encodeURIComponent(e.value)}`}
                    className="deck-card group flex items-center gap-3 rounded-[4px] bg-[#23262e] px-4 py-2.5 transition-colors hover:bg-[#2b2f38]"
                    title={e.value}
                  >
                    <span className="min-w-0 flex-1 truncate text-[15px] font-semibold text-bright">{e.value}</span>
                    <span className="w-24 shrink-0 text-right text-[13px] tabular-nums text-dim">{tv("gameCount", { count: e.count })}</span>
                  </Link>
                ))}
              </div>
            ) : (
              <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">
                {d.entries.map((e) => (
                  <CategoryTile
                    key={e.value}
                    href={`/collections/virtual/${d.key}/${encodeURIComponent(e.value)}`}
                    name={e.value}
                    count={e.count}
                    covers={e.covers}
                  />
                ))}
              </div>
            )}
          </section>
        )
      )}
      {dimensions.length > 0 && dimensions.every((d) => d.entries.length === 0) && emptyVirtualNote && (
        <p className="mt-6 text-sm text-dim">{emptyVirtualNote}</p>
      )}
    </>
  );
}
