// Embeds ScreenScraper app (developer) credentials into the build as an
// AES-256-GCM blob. Run once, then rebuild:
//
//   node scripts/embed-ss-dev.mjs <devid> <devpassword>
//
// or, to keep them out of shell history:
//
//   SS_DEVID=xxx SS_DEVPASSWORD=yyy node scripts/embed-ss-dev.mjs
//
// Writes src/lib/providers/ssdev.generated.ts. The credentials are never
// printed, stored in the database, or returned by any API.

import crypto from "crypto";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const devid = process.argv[2] ?? process.env.SS_DEVID ?? "";
const devpassword = process.argv[3] ?? process.env.SS_DEVPASSWORD ?? "";

if (!devid || !devpassword) {
  console.error("Usage: node scripts/embed-ss-dev.mjs <devid> <devpassword>");
  console.error("   or: SS_DEVID=xxx SS_DEVPASSWORD=yyy node scripts/embed-ss-dev.mjs");
  process.exit(1);
}

// Must match blobKey() in src/lib/providers/ssdev.ts
const key = crypto.scryptSync(["gh", "ssdev", "v1"].join("."), "gamehub.ssdev.salt", 32);
const iv = crypto.randomBytes(12);
const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
const ciphertext = Buffer.concat([
  cipher.update(JSON.stringify({ devid, devpassword }), "utf8"),
  cipher.final(),
]);
const blob = Buffer.concat([iv, cipher.getAuthTag(), ciphertext]).toString("base64");

const target = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "lib",
  "providers",
  "ssdev.generated.ts"
);

fs.writeFileSync(
  target,
  `// Generated by scripts/embed-ss-dev.mjs — do not edit by hand.
// Holds GameHub's ScreenScraper app (developer) credentials as an
// AES-256-GCM blob so they never appear in plain text in the repo, the
// database, or any API response. Empty string = no embedded credentials.
export const SSDEV_BLOB = ${JSON.stringify(blob)};
`
);

console.log(`Embedded ScreenScraper dev credentials for "${devid}" into ssdev.generated.ts`);
console.log("Rebuild the app (npm run build / docker compose up -d --build) to ship them.");
