// Creates an empty ssdev.generated.ts when it's missing (fresh clones —
// the real one is gitignored and only lives in release builds). Runs
// automatically before every build via the package.json "prebuild" script.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const target = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "lib",
  "providers",
  "ssdev.generated.ts"
);

if (!fs.existsSync(target)) {
  fs.writeFileSync(
    target,
    `// Generated by scripts/embed-ss-dev.mjs — do not edit by hand.
// Holds GameHub's ScreenScraper app (developer) credentials as an
// AES-256-GCM blob so they never appear in plain text in the repo, the
// database, or any API response. Empty string = no embedded credentials.
export const SSDEV_BLOB = "";
`
  );
  console.log("created empty src/lib/providers/ssdev.generated.ts (no embedded credentials)");
}
